//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_infaz
    {
        public xerife_infaz()
        {
            this.xerife_filial = new HashSet<xerife_filial>();
        }
    
        public int infaz_id { get; set; }
        public int codigo_infaz { get; set; }
        public string descricao { get; set; }
        public string contato { get; set; }
        public string telefone { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
    }
}
