//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_plano_saude
    {
        public xerife_plano_saude()
        {
            this.xerife_folha_plano_saude_dependente = new HashSet<xerife_folha_plano_saude_dependente>();
            this.xerife_folha_plano_saude_funcionario = new HashSet<xerife_folha_plano_saude_funcionario>();
            this.xerife_plano_saude_dependente = new HashSet<xerife_plano_saude_dependente>();
            this.xerife_plano_saude_funcionario = new HashSet<xerife_plano_saude_funcionario>();
            this.xerife_plano_saude_filial = new HashSet<xerife_plano_saude_filial>();
        }
    
        public int plano_saude_id { get; set; }
        public string cnpj { get; set; }
        public string razao_social { get; set; }
        public string registro_ans { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_folha_plano_saude_dependente> xerife_folha_plano_saude_dependente { get; set; }
        public virtual ICollection<xerife_folha_plano_saude_funcionario> xerife_folha_plano_saude_funcionario { get; set; }
        public virtual ICollection<xerife_plano_saude_dependente> xerife_plano_saude_dependente { get; set; }
        public virtual ICollection<xerife_plano_saude_funcionario> xerife_plano_saude_funcionario { get; set; }
        public virtual ICollection<xerife_plano_saude_filial> xerife_plano_saude_filial { get; set; }
    }
}
