//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_saldo_anterior_produto
    {
        public int saldo_anterior_produto_id { get; set; }
        public decimal saldo { get; set; }
        public byte[] controlversion { get; set; }
        public int estoque_id { get; set; }
        public int produto_id { get; set; }
    
        public virtual xerife_estoque xerife_estoque { get; set; }
        public virtual xerife_produto xerife_produto { get; set; }
    }
}
