//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_modelo_nota_fiscal
    {
        public xerife_modelo_nota_fiscal()
        {
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
            this.xerife_nota_ct = new HashSet<xerife_nota_ct>();
        }
    
        public int modelo_nota_fiscal_id { get; set; }
        public string descricao { get; set; }
        public string tipo_padrao { get; set; }
        public int visualizacao { get; set; }
        public decimal aliquota { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
        public virtual ICollection<xerife_nota_ct> xerife_nota_ct { get; set; }
    }
}
