//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_patrimonio
    {
        public xerife_patrimonio()
        {
            this.xerife_lancamento_contabil = new HashSet<xerife_lancamento_contabil>();
            this.xerife_lancamento_contabil1 = new HashSet<xerife_lancamento_contabil>();
            this.xerife_saldo_patrimonio = new HashSet<xerife_saldo_patrimonio>();
        }
    
        public int patrimonio_id { get; set; }
        public int plano_centro_custo_id { get; set; }
        public string referencia { get; set; }
        public string descricao { get; set; }
        public string comentario { get; set; }
        public Nullable<System.DateTime> aquisicao { get; set; }
        public decimal taxa { get; set; }
        public decimal saldo_anterior { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil { get; set; }
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil1 { get; set; }
        public virtual ICollection<xerife_saldo_patrimonio> xerife_saldo_patrimonio { get; set; }
        public virtual xerife_plano_centro_custo xerife_plano_centro_custo { get; set; }
    }
}
