//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_schema
    {
        public int schema_id { get; set; }
        public string sistema { get; set; }
        public string versao { get; set; }
        public System.DateTime atualizacao { get; set; }
        public string modificacoes { get; set; }
        public string script_executado { get; set; }
        public string atualizador { get; set; }
    }
}
