//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_formula
    {
        public xerife_formula()
        {
            this.xerife_evento = new HashSet<xerife_evento>();
            this.xerife_item_regime_tributario = new HashSet<xerife_item_regime_tributario>();
        }
    
        public string formula_id { get; set; }
        public string descricao { get; set; }
        public string codigo_fonte { get; set; }
        public byte[] controlversion { get; set; }
        public bool debug_info { get; set; }
        public string bibliotecas { get; set; }
        public bool tabela_obrigatoria { get; set; }
        public bool media_obrigatoria { get; set; }
        public bool variavel_obrigatoria { get; set; }
        public string internal_type { get; set; }
    
        public virtual ICollection<xerife_evento> xerife_evento { get; set; }
        public virtual ICollection<xerife_item_regime_tributario> xerife_item_regime_tributario { get; set; }
    }
}
