//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_empresa_contabil
    {
        public int empresa_id { get; set; }
        public string mascara_plano { get; set; }
        public bool controle_filiais { get; set; }
        public bool controle_centro_custo { get; set; }
        public bool controle_lote { get; set; }
        public bool lancamento_automatizado { get; set; }
        public string nome_moeda { get; set; }
        public decimal valor_moeda { get; set; }
        public bool usar_digito_verificador { get; set; }
        public Nullable<int> plano_conta_id_prejuizo { get; set; }
        public Nullable<int> plano_conta_id_lucro { get; set; }
        public Nullable<int> plano_conta_id_resultado { get; set; }
        public Nullable<int> plano_conta_id_depreciacao { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> plano_conta_id_ir { get; set; }
        public Nullable<int> plano_conta_id_csocial { get; set; }
        public int lancamento_fora_exercicio { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta1 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta2 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta3 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta4 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta5 { get; set; }
    }
}
