//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_sped_c460
    {
        public xerife_sped_c460()
        {
            this.xerife_sped_c470 = new HashSet<xerife_sped_c470>();
        }
    
        public int sped_c460_id { get; set; }
        public string codigo_modelo { get; set; }
        public int codigo_situacao { get; set; }
        public int numero_documento { get; set; }
        public Nullable<System.DateTime> data_emissao { get; set; }
        public decimal valor_total { get; set; }
        public decimal total_pis { get; set; }
        public decimal valor_cofins { get; set; }
        public string cpf_cnpj { get; set; }
        public string nome_cpf_cnpj { get; set; }
        public string chave_cfe { get; set; }
        public int numero_ccf { get; set; }
        public int lancamento_fiscal_id { get; set; }
    
        public virtual xerife_lancamento_fiscal xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_sped_c470> xerife_sped_c470 { get; set; }
    }
}
