//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_requisicao
    {
        public xerife_requisicao()
        {
            this.xerife_movimentacao_requisicao = new HashSet<xerife_movimentacao_requisicao>();
        }
    
        public int requisicao_id { get; set; }
        public int tipo { get; set; }
        public System.DateTime data { get; set; }
        public string solicitante { get; set; }
        public int prioridade { get; set; }
        public int solucao { get; set; }
        public int situacao { get; set; }
        public Nullable<System.DateTime> data_revisao { get; set; }
        public string revisor { get; set; }
        public int origem { get; set; }
        public Nullable<System.DateTime> vencimento { get; set; }
        public int assunto_requisicao_id { get; set; }
        public Nullable<int> filial_id { get; set; }
        public byte[] xml { get; set; }
    
        public virtual xerife_assunto_requisicao xerife_assunto_requisicao { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual ICollection<xerife_movimentacao_requisicao> xerife_movimentacao_requisicao { get; set; }
    }
}
