//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_titulo
    {
        public xerife_titulo()
        {
            this.xerife_item_parcela = new HashSet<xerife_item_parcela>();
            this.xerife_parcela_servico = new HashSet<xerife_parcela_servico>();
            this.xerife_rateio_financeiro = new HashSet<xerife_rateio_financeiro>();
            this.xerife_titulo_tag = new HashSet<xerife_titulo_tag>();
            this.xerife_titulo1 = new HashSet<xerife_titulo>();
        }
    
        public int titulo_id { get; set; }
        public string numero_fatura { get; set; }
        public int referencia { get; set; }
        public System.DateTime data_processamento { get; set; }
        public System.DateTime vencimento { get; set; }
        public decimal valor { get; set; }
        public decimal valor_minimo { get; set; }
        public Nullable<System.DateTime> desconto_ate { get; set; }
        public decimal desconto { get; set; }
        public Nullable<System.DateTime> pagamento { get; set; }
        public decimal creditado { get; set; }
        public decimal multa { get; set; }
        public decimal juros { get; set; }
        public decimal tarifa_bancaria { get; set; }
        public int plano { get; set; }
        public int parcela { get; set; }
        public string instrucao1 { get; set; }
        public string instrucao2 { get; set; }
        public string instrucao3 { get; set; }
        public Nullable<System.DateTime> cancelamento { get; set; }
        public string motivo_cancelamento { get; set; }
        public string anotacao { get; set; }
        public Nullable<System.DateTime> vencimento_anterior { get; set; }
        public Nullable<decimal> valor_anterior { get; set; }
        public bool comissionado { get; set; }
        public Nullable<int> conta_bancaria_id { get; set; }
        public int filial_id { get; set; }
        public int parceiro_id { get; set; }
        public Nullable<int> centro_custo_id { get; set; }
        public Nullable<System.Guid> anexo_id { get; set; }
        public Nullable<int> arquivo_retorno_id { get; set; }
        public Nullable<int> arquivo_remessa_id { get; set; }
        public string tipo { get; set; }
        public string situacao { get; set; }
        public string usuario_inclusao { get; set; }
        public string usuario_quitacao { get; set; }
        public string usuario_cancelamento { get; set; }
        public byte[] controlversion { get; set; }
        public int conta_financeira_id { get; set; }
        public string numero_aprovacao_cartao { get; set; }
        public string numero_cheque { get; set; }
        public Nullable<int> banco_id_cheque { get; set; }
        public Nullable<int> parceiro_id_cheque { get; set; }
        public Nullable<int> titulo_id_principal { get; set; }
        public System.DateTime data_documento { get; set; }
        public int numero { get; set; }
        public Nullable<long> importacao_id { get; set; }
        public Nullable<int> extrato_id { get; set; }
        public Nullable<int> forma_pagamento_id { get; set; }
    
        public virtual xerife_arquivo_bancario xerife_arquivo_bancario { get; set; }
        public virtual xerife_arquivo_bancario xerife_arquivo_bancario1 { get; set; }
        public virtual xerife_banco xerife_banco { get; set; }
        public virtual xerife_centro_custo xerife_centro_custo { get; set; }
        public virtual xerife_conta_bancaria xerife_conta_bancaria { get; set; }
        public virtual xerife_conta_financeira xerife_conta_financeira { get; set; }
        public virtual xerife_extrato xerife_extrato { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_forma_pagamento xerife_forma_pagamento { get; set; }
        public virtual ICollection<xerife_item_parcela> xerife_item_parcela { get; set; }
        public virtual xerife_lancamento_importado xerife_lancamento_importado { get; set; }
        public virtual xerife_parceiro xerife_parceiro { get; set; }
        public virtual xerife_parceiro xerife_parceiro1 { get; set; }
        public virtual ICollection<xerife_parcela_servico> xerife_parcela_servico { get; set; }
        public virtual ICollection<xerife_rateio_financeiro> xerife_rateio_financeiro { get; set; }
        public virtual ICollection<xerife_titulo_tag> xerife_titulo_tag { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo1 { get; set; }
        public virtual xerife_titulo xerife_titulo2 { get; set; }
    }
}
