//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_funcionario
    {
        public xerife_funcionario()
        {
            this.xerife_alocacao_tomador = new HashSet<xerife_alocacao_tomador>();
            this.xerife_anotacao_funcionario = new HashSet<xerife_anotacao_funcionario>();
            this.xerife_atestado = new HashSet<xerife_atestado>();
            this.xerife_conducao_funcionario = new HashSet<xerife_conducao_funcionario>();
            this.xerife_dependente_funcionario = new HashSet<xerife_dependente_funcionario>();
            this.xerife_evento_funcionario = new HashSet<xerife_evento_funcionario>();
            this.xerife_falta = new HashSet<xerife_falta>();
            this.xerife_ferias = new HashSet<xerife_ferias>();
            this.xerife_folha = new HashSet<xerife_folha>();
            this.xerife_folha_plano_saude_funcionario = new HashSet<xerife_folha_plano_saude_funcionario>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_funcionario_inativo = new HashSet<xerife_funcionario_inativo>();
            this.xerife_plano_saude_funcionario = new HashSet<xerife_plano_saude_funcionario>();
            this.xerife_refeicao_funcionario = new HashSet<xerife_refeicao_funcionario>();
            this.xerife_rescisao = new HashSet<xerife_rescisao>();
            this.xerife_funcionario_situacao = new HashSet<xerife_funcionario_situacao>();
            this.xerife_situacao_folha = new HashSet<xerife_situacao_folha>();
            this.xerife_ppp = new HashSet<xerife_ppp>();
        }
    
        public int funcionario_id { get; set; }
        public int filial_id { get; set; }
        public int codigo { get; set; }
        public string matricula { get; set; }
        public byte[] controlversion { get; set; }
        public string foto { get; set; }
        public Nullable<System.Guid> anexo_id { get; set; }
        public string senha_portal { get; set; }
        public string salt_senha_portal { get; set; }
        public Nullable<int> sip_id { get; set; }
    
        public virtual ICollection<xerife_alocacao_tomador> xerife_alocacao_tomador { get; set; }
        public virtual ICollection<xerife_anotacao_funcionario> xerife_anotacao_funcionario { get; set; }
        public virtual ICollection<xerife_atestado> xerife_atestado { get; set; }
        public virtual ICollection<xerife_conducao_funcionario> xerife_conducao_funcionario { get; set; }
        public virtual ICollection<xerife_dependente_funcionario> xerife_dependente_funcionario { get; set; }
        public virtual ICollection<xerife_evento_funcionario> xerife_evento_funcionario { get; set; }
        public virtual ICollection<xerife_falta> xerife_falta { get; set; }
        public virtual ICollection<xerife_ferias> xerife_ferias { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual ICollection<xerife_folha> xerife_folha { get; set; }
        public virtual ICollection<xerife_folha_plano_saude_funcionario> xerife_folha_plano_saude_funcionario { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_funcionario_inativo> xerife_funcionario_inativo { get; set; }
        public virtual ICollection<xerife_plano_saude_funcionario> xerife_plano_saude_funcionario { get; set; }
        public virtual ICollection<xerife_refeicao_funcionario> xerife_refeicao_funcionario { get; set; }
        public virtual ICollection<xerife_rescisao> xerife_rescisao { get; set; }
        public virtual ICollection<xerife_funcionario_situacao> xerife_funcionario_situacao { get; set; }
        public virtual ICollection<xerife_situacao_folha> xerife_situacao_folha { get; set; }
        public virtual ICollection<xerife_ppp> xerife_ppp { get; set; }
        public virtual xerife_sip xerife_sip { get; set; }
    }
}
