//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_outras_receitas
    {
        public xerife_outras_receitas()
        {
            this.xerife_outras_receitas_item = new HashSet<xerife_outras_receitas_item>();
        }
    
        public int outras_receitas_id { get; set; }
        public int filial_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public decimal valor_irrf { get; set; }
        public decimal valor_receita_financeira { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual ICollection<xerife_outras_receitas_item> xerife_outras_receitas_item { get; set; }
    }
}
