//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_estorno
    {
        public xerife_estorno()
        {
            this.xerife_estorno_item = new HashSet<xerife_estorno_item>();
        }
    
        public int estorno_id { get; set; }
        public int filial_id { get; set; }
        public int imposto_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public int periodo { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_estorno_item> xerife_estorno_item { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_imposto xerife_imposto { get; set; }
    }
}
