//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_plano_filial
    {
        public xerife_plano_filial()
        {
            this.xerife_plano_centro_custo = new HashSet<xerife_plano_centro_custo>();
        }
    
        public int plano_filial_id { get; set; }
        public int filial_id { get; set; }
        public int plano_conta_id { get; set; }
        public bool ativo { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual ICollection<xerife_plano_centro_custo> xerife_plano_centro_custo { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta { get; set; }
    }
}
