//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_evento_programado
    {
        public xerife_evento_programado()
        {
            this.xerife_evento_programado_item = new HashSet<xerife_evento_programado_item>();
        }
    
        public int evento_programado_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_evento_programado_item> xerife_evento_programado_item { get; set; }
    }
}
