//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_dependente_funcionario
    {
        public xerife_dependente_funcionario()
        {
            this.xerife_folha_plano_saude_dependente = new HashSet<xerife_folha_plano_saude_dependente>();
            this.xerife_plano_saude_dependente = new HashSet<xerife_plano_saude_dependente>();
        }
    
        public int dependente_funcionario_id { get; set; }
        public int funcionario_id { get; set; }
        public Nullable<System.DateTime> data_inclusao { get; set; }
        public bool ativo { get; set; }
        public string nome { get; set; }
        public int grau_instrucao_id { get; set; }
        public string sexo { get; set; }
        public System.DateTime nascimento { get; set; }
        public Nullable<System.DateTime> data_certidao { get; set; }
        public string numero_cartorio { get; set; }
        public Nullable<System.DateTime> data_baixa { get; set; }
        public string numero_registro { get; set; }
        public string livro { get; set; }
        public int folha { get; set; }
        public int municipio_id { get; set; }
        public int tipo { get; set; }
        public int parentesco { get; set; }
        public byte[] controlversion { get; set; }
        public string cpf { get; set; }
    
        public virtual ICollection<xerife_folha_plano_saude_dependente> xerife_folha_plano_saude_dependente { get; set; }
        public virtual ICollection<xerife_plano_saude_dependente> xerife_plano_saude_dependente { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
        public virtual xerife_grau_instrucao xerife_grau_instrucao { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
    }
}
