//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_conducao_item
    {
        public int conducao_item_id { get; set; }
        public int conducao_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public decimal valor { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_conducao xerife_conducao { get; set; }
    }
}
