//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_permissao
    {
        public xerife_permissao()
        {
            this.xerife_permissao_regra = new HashSet<xerife_permissao_regra>();
        }
    
        public int permissao_id { get; set; }
        public string permissao { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_permissao_regra> xerife_permissao_regra { get; set; }
    }
}
