//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_categoria_financeira
    {
        public xerife_categoria_financeira()
        {
            this.xerife_conta_financeira = new HashSet<xerife_conta_financeira>();
            this.xerife_titulo_tag = new HashSet<xerife_titulo_tag>();
        }
    
        public int categoria_financeira_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_conta_financeira> xerife_conta_financeira { get; set; }
        public virtual ICollection<xerife_titulo_tag> xerife_titulo_tag { get; set; }
    }
}
