//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_gps
    {
        public xerife_gps()
        {
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_tomador = new HashSet<xerife_tomador>();
        }
    
        public int gps_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_tomador> xerife_tomador { get; set; }
    }
}
