//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_cnae
    {
        public xerife_cnae()
        {
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_filial1 = new HashSet<xerife_filial>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
        }
    
        public int cnae_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public decimal rat { get; set; }
        public string atividade_economica { get; set; }
        public decimal aliquota_previdenciaria { get; set; }
    
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial1 { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
    }
}
