//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_ii
    {
        public xerife_item_ii()
        {
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
        }
    
        public int item_imposto_importacao_id { get; set; }
        public decimal base_calculo { get; set; }
        public decimal despesas_aduaneiras { get; set; }
        public decimal valor_iof { get; set; }
        public decimal valor_imposto { get; set; }
    
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
    }
}
