//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_auditoria
    {
        public long auditoria_id { get; set; }
        public string descricao { get; set; }
        public int evento { get; set; }
        public System.DateTime data { get; set; }
        public string conteudo { get; set; }
        public string usuario { get; set; }
        public int categoria { get; set; }
        public string origem { get; set; }
        public Nullable<int> objectcode { get; set; }
        public string objecttype { get; set; }
    }
}
