//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_imposto
    {
        public xerife_imposto()
        {
            this.xerife_acumulador_fiscal = new HashSet<xerife_acumulador_fiscal>();
            this.xerife_acumulador_servico = new HashSet<xerife_acumulador_servico>();
            this.xerife_apuracao_imposto = new HashSet<xerife_apuracao_imposto>();
            this.xerife_deducoes = new HashSet<xerife_deducoes>();
            this.xerife_estorno = new HashSet<xerife_estorno>();
            this.xerife_item_regime_tributario = new HashSet<xerife_item_regime_tributario>();
        }
    
        public int imposto_id { get; set; }
        public string descricao { get; set; }
        public string descricao_impressao { get; set; }
        public int tipo_padrao { get; set; }
        public int visualizacao { get; set; }
        public int valor_contabil_base { get; set; }
        public int valor_contabil_imposto { get; set; }
        public int valor_contabil_isentas { get; set; }
        public int valor_contabil_outras { get; set; }
        public bool agrupar_por_filiais { get; set; }
        public byte[] controlversion { get; set; }
        public int codigo { get; set; }
    
        public virtual ICollection<xerife_acumulador_fiscal> xerife_acumulador_fiscal { get; set; }
        public virtual ICollection<xerife_acumulador_servico> xerife_acumulador_servico { get; set; }
        public virtual ICollection<xerife_apuracao_imposto> xerife_apuracao_imposto { get; set; }
        public virtual ICollection<xerife_deducoes> xerife_deducoes { get; set; }
        public virtual ICollection<xerife_estorno> xerife_estorno { get; set; }
        public virtual ICollection<xerife_item_regime_tributario> xerife_item_regime_tributario { get; set; }
    }
}
