//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_arquivo_bancario
    {
        public xerife_arquivo_bancario()
        {
            this.xerife_extrato = new HashSet<xerife_extrato>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
            this.xerife_titulo1 = new HashSet<xerife_titulo>();
        }
    
        public int arquivo_bancario_id { get; set; }
        public string arquivo { get; set; }
        public int filial_id { get; set; }
        public int tipo { get; set; }
        public byte[] controlversion { get; set; }
        public System.DateTime data_envio { get; set; }
    
        public virtual ICollection<xerife_extrato> xerife_extrato { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo1 { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
    }
}
