//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_favorito
    {
        public int favorito_id { get; set; }
        public string favorito { get; set; }
        public byte[] controlversion { get; set; }
        public string usuario { get; set; }
    }
}
