//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_lancamento_importado
    {
        public xerife_lancamento_importado()
        {
            this.xerife_lancamento_contabil = new HashSet<xerife_lancamento_contabil>();
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public long importacao_id { get; set; }
        public string descricao { get; set; }
        public string usuario { get; set; }
        public System.DateTime data { get; set; }
        public string nome_arquivo { get; set; }
        public int empresa_id { get; set; }
        public byte[] controlversion { get; set; }
        public int codigo_importacao { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
    }
}
