//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_campo_usuario
    {
        public int campo_usuario_id { get; set; }
        public int campo_id { get; set; }
        public string tela { get; set; }
        public int tamanho { get; set; }
        public bool auto_tamanho { get; set; }
        public string usuario { get; set; }
        public string descricao_customizada { get; set; }
        public string formato_customizado { get; set; }
        public byte[] controlversion { get; set; }
        public int ordem { get; set; }
    
        public virtual xerife_tabela_campo xerife_tabela_campo { get; set; }
    }
}
