//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_contra_partida
    {
        public int contra_partida_id { get; set; }
        public int historico_contabil_id { get; set; }
        public int empresa_id { get; set; }
        public Nullable<int> plano_conta_credito_id { get; set; }
        public Nullable<int> plano_conta_debito_id { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual xerife_historico_contabil xerife_historico_contabil { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta1 { get; set; }
    }
}
