//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_issqn
    {
        public xerife_item_issqn()
        {
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
        }
    
        public int item_issqn_id { get; set; }
        public decimal base_calculo { get; set; }
        public decimal aliquota { get; set; }
        public decimal valor_issqn { get; set; }
        public int tabela_servico_id { get; set; }
        public int municipio_id { get; set; }
        public int situacao_tributaria { get; set; }
    
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_tabela_servico xerife_tabela_servico { get; set; }
    }
}
