//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_responsavel_registro_ppp
    {
        public int responsavel_id { get; set; }
        public string nome { get; set; }
        public string nit { get; set; }
        public string registro_classe { get; set; }
        public System.DateTime data_inicial { get; set; }
        public Nullable<System.DateTime> data_final { get; set; }
        public int tipo_responsavel { get; set; }
        public int ppp_id { get; set; }
    
        public virtual xerife_ppp xerife_ppp { get; set; }
    }
}
