//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_forma_pagamento
    {
        public xerife_forma_pagamento()
        {
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int forma_pagamento_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public int moeda_id { get; set; }
        public int empresa_id { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual xerife_moeda xerife_moeda { get; set; }
    }
}
