//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_sindicato
    {
        public xerife_sindicato()
        {
            this.xerife_evento_sindicato = new HashSet<xerife_evento_sindicato>();
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_piso_salarial = new HashSet<xerife_piso_salarial>();
            this.xerife_sindicato_parametro = new HashSet<xerife_sindicato_parametro>();
        }
    
        public int sindicato_id { get; set; }
        public string codigo { get; set; }
        public string razao_social { get; set; }
        public string fantasia { get; set; }
        public string cnpj { get; set; }
        public decimal valor_limite { get; set; }
        public int idade_maxima_auxilio_creche { get; set; }
        public decimal piso_salarial { get; set; }
        public int piso_salarial_apartir { get; set; }
        public int mes_base { get; set; }
        public int tipo_media_ferias { get; set; }
        public int tipo_media_13_salario { get; set; }
        public int tipo_media_rescisao { get; set; }
        public decimal horas_maxima_acumula { get; set; }
        public Nullable<int> indice_id_rescisao { get; set; }
        public Nullable<int> indice_id_13 { get; set; }
        public Nullable<int> indice_id_ferias { get; set; }
        public string endereco { get; set; }
        public string endereco_numero { get; set; }
        public string bairro { get; set; }
        public string complemento { get; set; }
        public string cep { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public int limite_anuenio { get; set; }
        public int limite_bienio { get; set; }
        public int limite_trienio { get; set; }
        public int limite_quiquenio { get; set; }
        public Nullable<System.DateTime> admissao_referencia { get; set; }
    
        public virtual ICollection<xerife_evento_sindicato> xerife_evento_sindicato { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual xerife_indice xerife_indice { get; set; }
        public virtual xerife_indice xerife_indice1 { get; set; }
        public virtual xerife_indice xerife_indice2 { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual ICollection<xerife_piso_salarial> xerife_piso_salarial { get; set; }
        public virtual ICollection<xerife_sindicato_parametro> xerife_sindicato_parametro { get; set; }
    }
}
