//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_ciap
    {
        public xerife_ciap()
        {
            this.xerife_ciap_item = new HashSet<xerife_ciap_item>();
        }
    
        public int ciap_id { get; set; }
        public string descricao { get; set; }
        public decimal valor_credito { get; set; }
        public int numero_lre { get; set; }
        public int folha_lre { get; set; }
        public int lancamento_fiscal_id { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_ciap_item> xerife_ciap_item { get; set; }
        public virtual xerife_lancamento_fiscal xerife_lancamento_fiscal { get; set; }
    }
}
