//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_atestado
    {
        public int atestado_id { get; set; }
        public int funcionario_id { get; set; }
        public System.DateTime afastamento { get; set; }
        public System.DateTime retorno { get; set; }
        public int motivo { get; set; }
        public string anotacoes { get; set; }
        public string cide { get; set; }
    
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
