//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_regime_tributario
    {
        public xerife_regime_tributario()
        {
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_item_regime_tributario = new HashSet<xerife_item_regime_tributario>();
            this.xerife_parceiro = new HashSet<xerife_parceiro>();
            this.xerife_tomador = new HashSet<xerife_tomador>();
        }
    
        public int regime_tributario_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public int tipo_regime_estadual { get; set; }
        public int tipo_regime_federal { get; set; }
    
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_item_regime_tributario> xerife_item_regime_tributario { get; set; }
        public virtual ICollection<xerife_parceiro> xerife_parceiro { get; set; }
        public virtual ICollection<xerife_tomador> xerife_tomador { get; set; }
    }
}
