//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_centro_custo
    {
        public xerife_centro_custo()
        {
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
            this.xerife_plano_centro_custo = new HashSet<xerife_plano_centro_custo>();
            this.xerife_rateio_financeiro = new HashSet<xerife_rateio_financeiro>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int centro_custo_id { get; set; }
        public int empresa_id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public bool padrao { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
        public virtual ICollection<xerife_plano_centro_custo> xerife_plano_centro_custo { get; set; }
        public virtual ICollection<xerife_rateio_financeiro> xerife_rateio_financeiro { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
    }
}
