//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_municipio
    {
        public xerife_municipio()
        {
            this.xerife_contador = new HashSet<xerife_contador>();
            this.xerife_dependente_funcionario = new HashSet<xerife_dependente_funcionario>();
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_funcionario_dados1 = new HashSet<xerife_funcionario_dados>();
            this.xerife_funcionario_dados2 = new HashSet<xerife_funcionario_dados>();
            this.xerife_item_issqn = new HashSet<xerife_item_issqn>();
            this.xerife_item_transporte = new HashSet<xerife_item_transporte>();
            this.xerife_parceiro = new HashSet<xerife_parceiro>();
            this.xerife_parceiro1 = new HashSet<xerife_parceiro>();
            this.xerife_sindicato = new HashSet<xerife_sindicato>();
            this.xerife_tomador = new HashSet<xerife_tomador>();
        }
    
        public int municipio_id { get; set; }
        public string nome { get; set; }
        public int uf_id { get; set; }
        public byte[] controlversion { get; set; }
        public int codigo_ibge { get; set; }
        public int codigo_dipj { get; set; }
        public int codigo_dma { get; set; }
        public string ws_nfse_envia_lote_producao { get; set; }
        public string ws_nfse_consulta_situacao_lote_producao { get; set; }
        public string ws_nfse_envia_lote_homologacao { get; set; }
        public string ws_nfse_consulta_situacao_lote_homologacao { get; set; }
        public string ws_nfse_consulta_homologacao { get; set; }
        public string ws_nfse_consulta_producao { get; set; }
    
        public virtual ICollection<xerife_contador> xerife_contador { get; set; }
        public virtual ICollection<xerife_dependente_funcionario> xerife_dependente_funcionario { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados1 { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados2 { get; set; }
        public virtual ICollection<xerife_item_issqn> xerife_item_issqn { get; set; }
        public virtual ICollection<xerife_item_transporte> xerife_item_transporte { get; set; }
        public virtual ICollection<xerife_parceiro> xerife_parceiro { get; set; }
        public virtual ICollection<xerife_parceiro> xerife_parceiro1 { get; set; }
        public virtual ICollection<xerife_sindicato> xerife_sindicato { get; set; }
        public virtual ICollection<xerife_tomador> xerife_tomador { get; set; }
        public virtual xerife_uf xerife_uf { get; set; }
    }
}
