//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_ipi
    {
        public xerife_item_ipi()
        {
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
        }
    
        public int item_ipi_id { get; set; }
        public int situacao_tributaria { get; set; }
        public decimal base_calculo { get; set; }
        public decimal aliquota { get; set; }
        public decimal valor_ipi { get; set; }
        public int tipo_calculo { get; set; }
        public decimal quantidade { get; set; }
        public decimal valor_unitario { get; set; }
        public string classe_cigarro { get; set; }
        public string enquadramento_legal { get; set; }
        public string cnpj_produtor { get; set; }
        public string numero_selo { get; set; }
        public int quantidade_selo { get; set; }
    
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
    }
}
