//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_integracao_fiscal
    {
        public int integracao_id { get; set; }
        public int tipo { get; set; }
        public string codigo_fiscal { get; set; }
        public int detalhamento_fiscal { get; set; }
        public int forma_pagamento { get; set; }
        public int tipo_imposto { get; set; }
        public int codigo_imposto { get; set; }
        public string especie { get; set; }
        public string serie { get; set; }
        public int tipo_valor { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_integracao xerife_integracao { get; set; }
    }
}
