//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_codigo_fiscal
    {
        public xerife_codigo_fiscal()
        {
            this.xerife_acumulador_fiscal = new HashSet<xerife_acumulador_fiscal>();
            this.xerife_item_fiscal = new HashSet<xerife_item_fiscal>();
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
            this.xerife_item_transporte = new HashSet<xerife_item_transporte>();
            this.xerife_mapeamento_tabela = new HashSet<xerife_mapeamento_tabela>();
            this.xerife_sped_c470 = new HashSet<xerife_sped_c470>();
            this.xerife_sped_c490 = new HashSet<xerife_sped_c490>();
        }
    
        public int codigo_fiscal_id { get; set; }
        public string codigo_fiscal { get; set; }
        public string tipo { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public bool exigir_detalhamento_fiscal { get; set; }
        public int classe_fiscal_id { get; set; }
    
        public virtual ICollection<xerife_acumulador_fiscal> xerife_acumulador_fiscal { get; set; }
        public virtual xerife_classe_fiscal xerife_classe_fiscal { get; set; }
        public virtual ICollection<xerife_item_fiscal> xerife_item_fiscal { get; set; }
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
        public virtual ICollection<xerife_item_transporte> xerife_item_transporte { get; set; }
        public virtual ICollection<xerife_mapeamento_tabela> xerife_mapeamento_tabela { get; set; }
        public virtual ICollection<xerife_sped_c470> xerife_sped_c470 { get; set; }
        public virtual ICollection<xerife_sped_c490> xerife_sped_c490 { get; set; }
    }
}
