//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_conta_financeira
    {
        public xerife_conta_financeira()
        {
            this.xerife_rateio_financeiro = new HashSet<xerife_rateio_financeiro>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int conta_financeira_id { get; set; }
        public string descricao { get; set; }
        public string numero_contrato { get; set; }
        public string anotacao { get; set; }
        public int filial_id { get; set; }
        public int categoria_financeira_id { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_categoria_financeira xerife_categoria_financeira { get; set; }
        public virtual ICollection<xerife_rateio_financeiro> xerife_rateio_financeiro { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
    }
}
