//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_conta_bancaria
    {
        public xerife_conta_bancaria()
        {
            this.xerife_extrato = new HashSet<xerife_extrato>();
            this.xerife_parceiro = new HashSet<xerife_parceiro>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int conta_bancaria_id { get; set; }
        public string descricao { get; set; }
        public string numero { get; set; }
        public string dac_numero { get; set; }
        public string agencia { get; set; }
        public string dac_agencia { get; set; }
        public string carteira { get; set; }
        public decimal tarifa_bancaria { get; set; }
        public string codigo_autorizacao { get; set; }
        public int contador_remessa { get; set; }
        public string gerente { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string email { get; set; }
        public string anotacao { get; set; }
        public Nullable<int> banco_id { get; set; }
        public int filial_id { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> moeda_id { get; set; }
        public string codigo_autorizacao_folha { get; set; }
        public int tipo { get; set; }
    
        public virtual xerife_banco xerife_banco { get; set; }
        public virtual ICollection<xerife_extrato> xerife_extrato { get; set; }
        public virtual ICollection<xerife_parceiro> xerife_parceiro { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_moeda xerife_moeda { get; set; }
    }
}
