//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_ciap_item
    {
        public int ciap_item_id { get; set; }
        public int ciap_id { get; set; }
        public System.DateTime data_credito { get; set; }
        public decimal valor_credito { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_ciap xerife_ciap { get; set; }
    }
}
