//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_grau_instrucao
    {
        public xerife_grau_instrucao()
        {
            this.xerife_dependente_funcionario = new HashSet<xerife_dependente_funcionario>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
        }
    
        public int grau_instrucao_id { get; set; }
        public string descricao { get; set; }
        public int tipo_padrao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_dependente_funcionario> xerife_dependente_funcionario { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
    }
}
