//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_mapa_tributario
    {
        public int mapa_tributario_id { get; set; }
        public decimal aliquota { get; set; }
        public int uf_id { get; set; }
        public int uf_id_destino { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_uf xerife_uf { get; set; }
        public virtual xerife_uf xerife_uf1 { get; set; }
    }
}
