//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_situacao_folha
    {
        public long situacao_folha_id { get; set; }
        public int situacao { get; set; }
        public string exercicio { get; set; }
        public int funcionario_id { get; set; }
        public int agrupamento { get; set; }
    
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
