//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_parcela
    {
        public int item_parcela_id { get; set; }
        public int lancamento_fiscal_id { get; set; }
        public int plano { get; set; }
        public int parcela { get; set; }
        public decimal valor { get; set; }
        public System.DateTime vencimento { get; set; }
        public int moeda_id { get; set; }
        public byte[] controlversion { get; set; }
        public string numero_duplicata { get; set; }
        public Nullable<int> titulo_id { get; set; }
    
        public virtual xerife_lancamento_fiscal xerife_lancamento_fiscal { get; set; }
        public virtual xerife_moeda xerife_moeda { get; set; }
        public virtual xerife_titulo xerife_titulo { get; set; }
    }
}
