//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_estoque
    {
        public xerife_estoque()
        {
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_saldo_anterior_produto = new HashSet<xerife_saldo_anterior_produto>();
            this.xerife_saldo_produto = new HashSet<xerife_saldo_produto>();
        }
    
        public int estoque_id { get; set; }
        public string descricao { get; set; }
        public int filial_id { get; set; }
        public bool padrao { get; set; }
        public bool ativo { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_saldo_anterior_produto> xerife_saldo_anterior_produto { get; set; }
        public virtual ICollection<xerife_saldo_produto> xerife_saldo_produto { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
    }
}
