//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_vale_refeicao
    {
        public xerife_vale_refeicao()
        {
            this.xerife_refeicao_funcionario = new HashSet<xerife_refeicao_funcionario>();
            this.xerife_vale_valor = new HashSet<xerife_vale_valor>();
        }
    
        public int vale_refeicao_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_refeicao_funcionario> xerife_refeicao_funcionario { get; set; }
        public virtual ICollection<xerife_vale_valor> xerife_vale_valor { get; set; }
    }
}
