//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_permissao_filial
    {
        public int permissao_filial_id { get; set; }
        public int filial_id { get; set; }
        public int usuario_id { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_usuario xerife_usuario { get; set; }
    }
}
