//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_estorno_item
    {
        public int estorno_item_id { get; set; }
        public int estorno_id { get; set; }
        public int item_id { get; set; }
        public decimal outros_creditos { get; set; }
        public string outros_creditos_descricao { get; set; }
        public decimal estorno_debitos { get; set; }
        public string estorno_debitos_descricao { get; set; }
        public decimal outros_debitos { get; set; }
        public string outros_debitos_descricao { get; set; }
        public decimal estorno_creditos { get; set; }
        public string estorno_creditos_descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_estorno xerife_estorno { get; set; }
    }
}
