//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_moeda
    {
        public xerife_moeda()
        {
            this.xerife_conta_bancaria = new HashSet<xerife_conta_bancaria>();
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_filial1 = new HashSet<xerife_filial>();
            this.xerife_forma_pagamento = new HashSet<xerife_forma_pagamento>();
            this.xerife_item_parcela = new HashSet<xerife_item_parcela>();
            this.xerife_parcela_servico = new HashSet<xerife_parcela_servico>();
        }
    
        public int moeda_id { get; set; }
        public string descricao { get; set; }
        public int tipo_padrao { get; set; }
        public byte[] controlversion { get; set; }
        public bool avista { get; set; }
    
        public virtual ICollection<xerife_conta_bancaria> xerife_conta_bancaria { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial1 { get; set; }
        public virtual ICollection<xerife_forma_pagamento> xerife_forma_pagamento { get; set; }
        public virtual ICollection<xerife_item_parcela> xerife_item_parcela { get; set; }
        public virtual ICollection<xerife_parcela_servico> xerife_parcela_servico { get; set; }
    }
}
