//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_empresa
    {
        public xerife_empresa()
        {
            this.xerife_centro_custo = new HashSet<xerife_centro_custo>();
            this.xerife_contra_partida = new HashSet<xerife_contra_partida>();
            this.xerife_departamento = new HashSet<xerife_departamento>();
            this.xerife_detalhamento_fiscal = new HashSet<xerife_detalhamento_fiscal>();
            this.xerife_ecf = new HashSet<xerife_ecf>();
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_forma_pagamento = new HashSet<xerife_forma_pagamento>();
            this.xerife_historico_contabil = new HashSet<xerife_historico_contabil>();
            this.xerife_integracao = new HashSet<xerife_integracao>();
            this.xerife_lancamento_importado = new HashSet<xerife_lancamento_importado>();
            this.xerife_lote_contabil = new HashSet<xerife_lote_contabil>();
            this.xerife_parceiro = new HashSet<xerife_parceiro>();
            this.xerife_plano_conta = new HashSet<xerife_plano_conta>();
            this.xerife_produto = new HashSet<xerife_produto>();
            this.xerife_tomador = new HashSet<xerife_tomador>();
            this.xerife_total_contabil_usuario = new HashSet<xerife_total_contabil_usuario>();
            this.xerife_total_contabil = new HashSet<xerife_total_contabil>();
        }
    
        public int empresa_id { get; set; }
        public string razao_social { get; set; }
        public string fantasia { get; set; }
        public bool ativo { get; set; }
        public System.DateTime data_fundacao { get; set; }
        public byte[] controlversion { get; set; }
        public string logomarca { get; set; }
    
        public virtual ICollection<xerife_centro_custo> xerife_centro_custo { get; set; }
        public virtual ICollection<xerife_contra_partida> xerife_contra_partida { get; set; }
        public virtual ICollection<xerife_departamento> xerife_departamento { get; set; }
        public virtual ICollection<xerife_detalhamento_fiscal> xerife_detalhamento_fiscal { get; set; }
        public virtual ICollection<xerife_ecf> xerife_ecf { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_forma_pagamento> xerife_forma_pagamento { get; set; }
        public virtual ICollection<xerife_historico_contabil> xerife_historico_contabil { get; set; }
        public virtual ICollection<xerife_integracao> xerife_integracao { get; set; }
        public virtual ICollection<xerife_lancamento_importado> xerife_lancamento_importado { get; set; }
        public virtual ICollection<xerife_lote_contabil> xerife_lote_contabil { get; set; }
        public virtual ICollection<xerife_parceiro> xerife_parceiro { get; set; }
        public virtual ICollection<xerife_plano_conta> xerife_plano_conta { get; set; }
        public virtual ICollection<xerife_produto> xerife_produto { get; set; }
        public virtual ICollection<xerife_tomador> xerife_tomador { get; set; }
        public virtual ICollection<xerife_total_contabil_usuario> xerife_total_contabil_usuario { get; set; }
        public virtual xerife_empresa_comercial xerife_empresa_comercial { get; set; }
        public virtual xerife_empresa_contabil xerife_empresa_contabil { get; set; }
        public virtual xerife_empresa_fiscal xerife_empresa_fiscal { get; set; }
        public virtual xerife_empresa_folha xerife_empresa_folha { get; set; }
        public virtual ICollection<xerife_total_contabil> xerife_total_contabil { get; set; }
    }
}
