//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_rescisao
    {
        public int rescisao_id { get; set; }
        public byte[] controlversion { get; set; }
        public int funcionario_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public System.DateTime data_rescisao { get; set; }
        public System.DateTime data_aviso { get; set; }
        public int tipo { get; set; }
        public int tipo_aviso { get; set; }
        public int cod_saque { get; set; }
        public decimal fgts { get; set; }
        public decimal fgts_anterior { get; set; }
        public int tipo_termino_contrato { get; set; }
        public Nullable<System.DateTime> data_homologacao { get; set; }
        public bool decimo_terceiro { get; set; }
        public string descricao_afastamento { get; set; }
        public bool grfc { get; set; }
        public bool complementar { get; set; }
        public int meses_seguro { get; set; }
        public bool abater_faltas { get; set; }
    
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
