//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_regra_acesso_item
    {
        public int regra_acesso_item_id { get; set; }
        public int dia { get; set; }
        public Nullable<System.DateTime> entrada { get; set; }
        public Nullable<System.DateTime> saida_intervalo { get; set; }
        public Nullable<System.DateTime> entrada_intervalo { get; set; }
        public Nullable<System.DateTime> saida { get; set; }
        public bool autodesconectar { get; set; }
        public byte[] controlversion { get; set; }
        public int regra_acesso_id { get; set; }
        public bool ativo { get; set; }
    
        public virtual xerife_regra_acesso xerife_regra_acesso { get; set; }
    }
}
