//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_ecf
    {
        public xerife_ecf()
        {
            this.xerife_item_ecf = new HashSet<xerife_item_ecf>();
        }
    
        public int ecf_id { get; set; }
        public string descricao { get; set; }
        public string numero { get; set; }
        public string serie_fabricacao { get; set; }
        public int empresa_id { get; set; }
        public byte[] controlversion { get; set; }
        public string modelo { get; set; }
        public string numero_caixa { get; set; }
    
        public virtual ICollection<xerife_item_ecf> xerife_item_ecf { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
    }
}
