//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_assunto_requisicao
    {
        public xerife_assunto_requisicao()
        {
            this.xerife_requisicao = new HashSet<xerife_requisicao>();
        }
    
        public int assunto_requisicao_id { get; set; }
        public string descricao { get; set; }
    
        public virtual ICollection<xerife_requisicao> xerife_requisicao { get; set; }
    }
}
