//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_ppp
    {
        public xerife_ppp()
        {
            this.xerife_exame_medico = new HashSet<xerife_exame_medico>();
            this.xerife_exposicao_fator_risco = new HashSet<xerife_exposicao_fator_risco>();
            this.xerife_profissiografia = new HashSet<xerife_profissiografia>();
            this.xerife_responsavel_registro_ppp = new HashSet<xerife_responsavel_registro_ppp>();
        }
    
        public int ppp_id { get; set; }
        public Nullable<System.DateTime> data_registro { get; set; }
        public string numero_categoria { get; set; }
        public Nullable<System.DateTime> data_registro1 { get; set; }
        public string numero_categoria1 { get; set; }
        public string regime_revezamento { get; set; }
        public int funcionario_id { get; set; }
        public bool hierarquia_item_9354 { get; set; }
        public bool funcionamento_epi { get; set; }
        public bool validade_certificado { get; set; }
        public bool periodicidade_troca { get; set; }
        public bool meios_higienizacao { get; set; }
        public string observacao { get; set; }
        public string br_pdh { get; set; }
    
        public virtual ICollection<xerife_exame_medico> xerife_exame_medico { get; set; }
        public virtual ICollection<xerife_exposicao_fator_risco> xerife_exposicao_fator_risco { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
        public virtual ICollection<xerife_profissiografia> xerife_profissiografia { get; set; }
        public virtual ICollection<xerife_responsavel_registro_ppp> xerife_responsavel_registro_ppp { get; set; }
    }
}
