//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_sip
    {
        public xerife_sip()
        {
            this.xerife_funcionario = new HashSet<xerife_funcionario>();
        }
    
        public int sip_id { get; set; }
        public Nullable<System.DateTime> data_ingresso_servico_publico { get; set; }
        public string ano_primeiro_emprego { get; set; }
        public string regime_contratacao { get; set; }
        public string chefia_direcao_encarregado { get; set; }
        public string atividade_meio_fim { get; set; }
        public string preenchimento_provimento { get; set; }
        public string acumulacao_cargo { get; set; }
        public string ultimo_cargo { get; set; }
        public Nullable<System.DateTime> data_promocao { get; set; }
        public string situacao_funcional_codigo { get; set; }
        public Nullable<System.DateTime> situacao_funcional_data_inicio { get; set; }
        public string faixa_referencia { get; set; }
        public bool sexta_parte { get; set; }
        public int qtd_quinquenio { get; set; }
        public int qtd_anuenio { get; set; }
        public bool regime_previdencia { get; set; }
        public string bloqueio_motivo { get; set; }
        public Nullable<System.DateTime> bloqueio_inicio { get; set; }
        public string tipo_beneficio_nao_servidor { get; set; }
        public bool liminar { get; set; }
        public bool acao_judicial { get; set; }
    
        public virtual ICollection<xerife_funcionario> xerife_funcionario { get; set; }
    }
}
