//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_lancamento_contabil
    {
        public long lancamento_id { get; set; }
        public long lote_id { get; set; }
        public long numero { get; set; }
        public Nullable<int> plano_centro_custo_debito_id { get; set; }
        public Nullable<int> plano_centro_custo_credito_id { get; set; }
        public Nullable<int> patrimonio_debito_id { get; set; }
        public Nullable<int> patrimonio_credito_id { get; set; }
        public System.DateTime data { get; set; }
        public decimal valor_debito { get; set; }
        public decimal valor_credito { get; set; }
        public decimal valor { get; set; }
        public string historico { get; set; }
        public int tipo_lancamento { get; set; }
        public int flag_lancamento { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> plano_conta_credito_id { get; set; }
        public Nullable<int> plano_conta_debito_id { get; set; }
        public System.DateTime data_lancamento { get; set; }
        public Nullable<int> codigo_importacao { get; set; }
        public string usuario { get; set; }
        public Nullable<long> importacao_id { get; set; }
    
        public virtual xerife_lancamento_importado xerife_lancamento_importado { get; set; }
        public virtual xerife_lote_contabil xerife_lote_contabil { get; set; }
        public virtual xerife_patrimonio xerife_patrimonio { get; set; }
        public virtual xerife_patrimonio xerife_patrimonio1 { get; set; }
        public virtual xerife_plano_centro_custo xerife_plano_centro_custo { get; set; }
        public virtual xerife_plano_centro_custo xerife_plano_centro_custo1 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta1 { get; set; }
    }
}
