//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_historico_contabil
    {
        public xerife_historico_contabil()
        {
            this.xerife_contra_partida = new HashSet<xerife_contra_partida>();
            this.xerife_integracao = new HashSet<xerife_integracao>();
        }
    
        public int historico_contabil_id { get; set; }
        public int empresa_id { get; set; }
        public string historico { get; set; }
        public int codigo { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_contra_partida> xerife_contra_partida { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_integracao> xerife_integracao { get; set; }
    }
}
