//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_ferias
    {
        public int ferias_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public System.DateTime inicio_aquisicao { get; set; }
        public System.DateTime fim_aquisicao { get; set; }
        public System.DateTime inicio_gozo { get; set; }
        public System.DateTime fim_gozo { get; set; }
        public System.DateTime data_aviso { get; set; }
        public System.DateTime data_pagamento { get; set; }
        public Nullable<System.DateTime> inicio_abono { get; set; }
        public Nullable<System.DateTime> fim_abono { get; set; }
        public int tipo { get; set; }
        public int funcionario_id { get; set; }
        public byte[] controlversion { get; set; }
        public int agrupamento { get; set; }
        public int agrupamento1 { get; set; }
        public int agrupamento2 { get; set; }
        public string anotacao { get; set; }
    
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
