//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_configuracao
    {
        public int configuracao_id { get; set; }
        public bool ativar_cadastra_se { get; set; }
        public Nullable<int> regra_id { get; set; }
        public string usuario_dominio { get; set; }
        public int porta { get; set; }
        public bool usa_ssl { get; set; }
        public string servidor_imap { get; set; }
        public string email { get; set; }
        public string senha { get; set; }
        public string salt_senha { get; set; }
        public int modulos_extras { get; set; }
        public bool imprime_data_relatorio { get; set; }
    
        public virtual xerife_regra xerife_regra { get; set; }
    }
}
