//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tomador
    {
        public xerife_tomador()
        {
            this.xerife_alocacao_tomador = new HashSet<xerife_alocacao_tomador>();
            this.xerife_evento_tomador = new HashSet<xerife_evento_tomador>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_tomador_mensal = new HashSet<xerife_tomador_mensal>();
        }
    
        public int tomador_id { get; set; }
        public int empresa_id { get; set; }
        public string razao_social { get; set; }
        public string fantasia { get; set; }
        public bool ativo { get; set; }
        public string cnpj_cei { get; set; }
        public int tipo { get; set; }
        public string endereco { get; set; }
        public string endereco_numero { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public Nullable<int> gps_id { get; set; }
        public Nullable<int> regime_tributario_id { get; set; }
    
        public virtual ICollection<xerife_alocacao_tomador> xerife_alocacao_tomador { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_evento_tomador> xerife_evento_tomador { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual xerife_gps xerife_gps { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_regime_tributario xerife_regime_tributario { get; set; }
        public virtual ICollection<xerife_tomador_mensal> xerife_tomador_mensal { get; set; }
    }
}
