//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_integracao
    {
        public int integracao_id { get; set; }
        public string descricao { get; set; }
        public int modelo { get; set; }
        public bool partida_dupla { get; set; }
        public Nullable<int> plano_conta_credito_id { get; set; }
        public Nullable<int> plano_conta_debito_id { get; set; }
        public int empresa_id { get; set; }
        public byte[] controlversion { get; set; }
        public int historico_contabil_id { get; set; }
        public bool importacao { get; set; }
        public Nullable<System.DateTime> data_importacao { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual xerife_historico_contabil xerife_historico_contabil { get; set; }
        public virtual xerife_integracao_fiscal xerife_integracao_fiscal { get; set; }
        public virtual xerife_integracao_generica xerife_integracao_generica { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta1 { get; set; }
    }
}
