//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tipo_extrato
    {
        public xerife_tipo_extrato()
        {
            this.xerife_extrato = new HashSet<xerife_extrato>();
        }
    
        public int tipo_extrato { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public bool integrar_contabilidade { get; set; }
    
        public virtual ICollection<xerife_extrato> xerife_extrato { get; set; }
    }
}
