//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_extrato
    {
        public xerife_extrato()
        {
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int extrato_id { get; set; }
        public System.DateTime lancamento { get; set; }
        public string historico { get; set; }
        public decimal valor { get; set; }
        public bool conciliado { get; set; }
        public string integracao { get; set; }
        public int conta_bancaria_id { get; set; }
        public int tipo_extrato { get; set; }
        public string tipo { get; set; }
        public Nullable<int> arquivo_bancario_id { get; set; }
        public byte[] controlversion { get; set; }
        public bool integrar_contabilidade { get; set; }
    
        public virtual xerife_arquivo_bancario xerife_arquivo_bancario { get; set; }
        public virtual xerife_conta_bancaria xerife_conta_bancaria { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual xerife_tipo_extrato xerife_tipo_extrato { get; set; }
    }
}
