//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_bloqueio_mensal
    {
        public int bloqueio_mensal_id { get; set; }
        public int filial_id { get; set; }
        public string exercicio { get; set; }
        public int modulo { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
    }
}
