//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_lote_contabil
    {
        public xerife_lote_contabil()
        {
            this.xerife_lancamento_contabil = new HashSet<xerife_lancamento_contabil>();
        }
    
        public long lote_id { get; set; }
        public string descricao { get; set; }
        public int empresa_id { get; set; }
        public long proximo_numero { get; set; }
        public decimal debito { get; set; }
        public byte[] controlversion { get; set; }
        public decimal credito { get; set; }
        public bool padrao { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil { get; set; }
    }
}
