//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_uf
    {
        public xerife_uf()
        {
            this.xerife_acumulador_fiscal = new HashSet<xerife_acumulador_fiscal>();
            this.xerife_acumulador_servico = new HashSet<xerife_acumulador_servico>();
            this.xerife_item_icms = new HashSet<xerife_item_icms>();
            this.xerife_item_transporte = new HashSet<xerife_item_transporte>();
            this.xerife_item_transporte1 = new HashSet<xerife_item_transporte>();
            this.xerife_mapa_tributario = new HashSet<xerife_mapa_tributario>();
            this.xerife_mapa_tributario1 = new HashSet<xerife_mapa_tributario>();
            this.xerife_municipio = new HashSet<xerife_municipio>();
            this.xerife_produto = new HashSet<xerife_produto>();
        }
    
        public int uf_id { get; set; }
        public string uf { get; set; }
        public string nome { get; set; }
        public byte[] controlversion { get; set; }
        public int nire { get; set; }
    
        public virtual ICollection<xerife_acumulador_fiscal> xerife_acumulador_fiscal { get; set; }
        public virtual ICollection<xerife_acumulador_servico> xerife_acumulador_servico { get; set; }
        public virtual ICollection<xerife_item_icms> xerife_item_icms { get; set; }
        public virtual ICollection<xerife_item_transporte> xerife_item_transporte { get; set; }
        public virtual ICollection<xerife_item_transporte> xerife_item_transporte1 { get; set; }
        public virtual ICollection<xerife_mapa_tributario> xerife_mapa_tributario { get; set; }
        public virtual ICollection<xerife_mapa_tributario> xerife_mapa_tributario1 { get; set; }
        public virtual ICollection<xerife_municipio> xerife_municipio { get; set; }
        public virtual ICollection<xerife_produto> xerife_produto { get; set; }
    }
}
