//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_ecf
    {
        public xerife_item_ecf()
        {
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
        }
    
        public int item_ecf_id { get; set; }
        public decimal gt_atual { get; set; }
        public int gt_reduzao_z { get; set; }
        public int gt_reinicio { get; set; }
        public byte[] controlversion { get; set; }
        public int ecf_id { get; set; }
        public Nullable<int> ultimo_doc_emitido { get; set; }
    
        public virtual xerife_ecf xerife_ecf { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
    }
}
