//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_funcionario_dados
    {
        public int funcionario_dados_id { get; set; }
        public int funcionario_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public string nome { get; set; }
        public Nullable<System.DateTime> data_nascimento { get; set; }
        public string sexo { get; set; }
        public string rg { get; set; }
        public string pis { get; set; }
        public string cpf { get; set; }
        public System.DateTime data_admissao { get; set; }
        public string pai { get; set; }
        public string mae { get; set; }
        public string titulo_eleitoral { get; set; }
        public string reservista { get; set; }
        public int deficiente { get; set; }
        public decimal salario { get; set; }
        public string tipo_salario { get; set; }
        public bool indexado_salario_minimo { get; set; }
        public Nullable<System.DateTime> data_aso { get; set; }
        public Nullable<System.DateTime> validate_aso { get; set; }
        public Nullable<System.DateTime> data_experiencia { get; set; }
        public int dias_vigencia_experiencia { get; set; }
        public Nullable<System.DateTime> data_aposentadoria { get; set; }
        public string numero_cnh { get; set; }
        public string categoria_cnh { get; set; }
        public Nullable<int> calendario_id { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public Nullable<int> municipio_id_nascimento { get; set; }
        public Nullable<int> horario_id { get; set; }
        public string numero_conta_bancaria { get; set; }
        public string numero_conta_fgts { get; set; }
        public string agencia_conta_fgts { get; set; }
        public string dac_numero_conta_fgts { get; set; }
        public string dac_agencia_conta_fgts { get; set; }
        public string agencia_conta_bancaria { get; set; }
        public string dac_numero_conta_bancaria { get; set; }
        public string dac_agencia_conta_bancaria { get; set; }
        public int tipo_conta_bancaria { get; set; }
        public Nullable<int> banco_id { get; set; }
        public Nullable<int> banco_id_fgts { get; set; }
        public Nullable<int> sindicato_id { get; set; }
        public Nullable<int> cargo_id { get; set; }
        public Nullable<int> departamento_id { get; set; }
        public Nullable<int> centro_custo_id { get; set; }
        public Nullable<int> tomador_id { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string complemento { get; set; }
        public string cep { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public string ramal { get; set; }
        public string celular { get; set; }
        public Nullable<int> nacionalidade_id { get; set; }
        public byte[] controlversion { get; set; }
        public int cor { get; set; }
        public int estado_civil { get; set; }
        public decimal horas_trabalho { get; set; }
        public string carteira_trabalho { get; set; }
        public Nullable<int> vinculo_id { get; set; }
        public string email { get; set; }
        public int tipo_admissao { get; set; }
        public Nullable<System.DateTime> data_admissao_transferencia { get; set; }
        public Nullable<int> categoria_id { get; set; }
        public decimal salario_adicional { get; set; }
        public int tipo_teto_salarial { get; set; }
        public Nullable<int> grau_instrucao_id { get; set; }
        public int tipo_cabelo { get; set; }
        public decimal altura { get; set; }
        public decimal peso { get; set; }
        public int tipo_olhos { get; set; }
        public string sinais { get; set; }
        public string rg_orgao { get; set; }
        public Nullable<System.DateTime> rg_emissao { get; set; }
        public string titulo_secao { get; set; }
        public string titulo_zona { get; set; }
        public string ctps_rural { get; set; }
        public string ctps_serie { get; set; }
        public string carteira_trabalho_serie { get; set; }
        public string carteira_trabalho_uf { get; set; }
        public Nullable<System.DateTime> validade_cnh { get; set; }
        public string carteira_exterior { get; set; }
        public string rg_exterior { get; set; }
        public int quantidade_filhos_brasil { get; set; }
        public Nullable<System.DateTime> data_chegada_brasil { get; set; }
        public string pais_naturalizado { get; set; }
        public string decreto_naturalizacao { get; set; }
        public bool casado_com_brasileiro { get; set; }
        public string conjuge { get; set; }
        public bool optante_fgts { get; set; }
        public Nullable<System.DateTime> data_opcao_fgts { get; set; }
        public Nullable<System.DateTime> data_retratacao_fgts { get; set; }
        public Nullable<System.DateTime> data_pis { get; set; }
        public Nullable<int> ocorrencia_id { get; set; }
        public bool contribuicao_sindical { get; set; }
        public string alvara_menor_aprendiz { get; set; }
        public string numero_endereco { get; set; }
        public int tipo_contrato_trabalho { get; set; }
        public decimal pensao_fgts { get; set; }
        public string apelido { get; set; }
        public string tipo_sanguineo { get; set; }
        public Nullable<System.DateTime> data_emissao_carteira_trabalho { get; set; }
        public Nullable<int> calendario_id_refeicao { get; set; }
        public Nullable<int> calendario_id_conducao { get; set; }
        public Nullable<int> calendario_id_dsr { get; set; }
        public Nullable<int> filial_transferencia_origem_id { get; set; }
        public decimal reducao_irrf { get; set; }
        public Nullable<int> municipio_id_titulo_eleitorial { get; set; }
    
        public virtual xerife_banco xerife_banco { get; set; }
        public virtual xerife_banco xerife_banco1 { get; set; }
        public virtual xerife_calendario xerife_calendario { get; set; }
        public virtual xerife_calendario xerife_calendario1 { get; set; }
        public virtual xerife_calendario xerife_calendario2 { get; set; }
        public virtual xerife_calendario xerife_calendario3 { get; set; }
        public virtual xerife_cargo xerife_cargo { get; set; }
        public virtual xerife_categoria xerife_categoria { get; set; }
        public virtual xerife_centro_custo xerife_centro_custo { get; set; }
        public virtual xerife_departamento xerife_departamento { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
        public virtual xerife_grau_instrucao xerife_grau_instrucao { get; set; }
        public virtual xerife_horario xerife_horario { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_municipio xerife_municipio1 { get; set; }
        public virtual xerife_municipio xerife_municipio2 { get; set; }
        public virtual xerife_nacionalidade xerife_nacionalidade { get; set; }
        public virtual xerife_ocorrencia xerife_ocorrencia { get; set; }
        public virtual xerife_sindicato xerife_sindicato { get; set; }
        public virtual xerife_tomador xerife_tomador { get; set; }
        public virtual xerife_vinculo xerife_vinculo { get; set; }
    }
}
