//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_exame_medico
    {
        public int exame_id { get; set; }
        public System.DateTime data { get; set; }
        public int indicacao_resultado { get; set; }
        public string tipo { get; set; }
        public string natureza { get; set; }
        public string exame { get; set; }
        public int ppp_id { get; set; }
    
        public virtual xerife_ppp xerife_ppp { get; set; }
    }
}
