//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_plano_saude_filial
    {
        public int plano_saude_filial_id { get; set; }
        public int plano_saude_id { get; set; }
        public int filial_id { get; set; }
        public string numero_apolice { get; set; }
        public Nullable<System.DateTime> data_contrato { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<System.DateTime> termino_contrato { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_plano_saude xerife_plano_saude { get; set; }
    }
}
