//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_calendario_item
    {
        public int calendario_item_id { get; set; }
        public int calendario_id { get; set; }
        public int ano { get; set; }
        public int mes { get; set; }
        public int dia { get; set; }
        public bool util { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_calendario xerife_calendario { get; set; }
    }
}
