//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tipo_parceiro
    {
        public xerife_tipo_parceiro()
        {
            this.xerife_parceiro = new HashSet<xerife_parceiro>();
        }
    
        public int tipo_parceiro_id { get; set; }
        public string descricao { get; set; }
        public bool uso_interno { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_parceiro> xerife_parceiro { get; set; }
    }
}
