//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_produto
    {
        public xerife_produto()
        {
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
            this.xerife_saldo_anterior_produto = new HashSet<xerife_saldo_anterior_produto>();
            this.xerife_saldo_produto = new HashSet<xerife_saldo_produto>();
            this.xerife_sped_c470 = new HashSet<xerife_sped_c470>();
        }
    
        public int produto_id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public int icms_situacao_tributaria_normal { get; set; }
        public int ex_tipi { get; set; }
        public int icms_situacao_tributaria_simples { get; set; }
        public int ncm { get; set; }
        public decimal icms_aliquota_saida { get; set; }
        public string ean_tributavel { get; set; }
        public int ipi_situacao_tributaria_entrada { get; set; }
        public int origem { get; set; }
        public decimal ipi_aliquota_entrada { get; set; }
        public string ean { get; set; }
        public int ipi_situacao_tributaria_saida { get; set; }
        public decimal valor_unitario { get; set; }
        public decimal quantidade_tributavel { get; set; }
        public decimal ipi_aliquota_saida { get; set; }
        public decimal valor_unitario_tributavel { get; set; }
        public int pis_situacao_tributaria_entrada { get; set; }
        public decimal pis_aliquota_entrada { get; set; }
        public int pis_situacao_tributaria_saida { get; set; }
        public decimal pis_aliquota_saida { get; set; }
        public int cofins_situacao_tributaria_entrada { get; set; }
        public decimal cofins_aliquota_entrada { get; set; }
        public int cofins_situacao_tributaria_saida { get; set; }
        public decimal cofins_aliquota_saida { get; set; }
        public byte[] controlversion { get; set; }
        public int empresa_id { get; set; }
        public int unidade_id { get; set; }
        public Nullable<int> unidade_tributavel_id { get; set; }
        public int regime { get; set; }
        public decimal aliquota_credito { get; set; }
        public int modelo_base_calculo_icms { get; set; }
        public int modelo_base_calculo_icms_st { get; set; }
        public decimal reducao_base_st { get; set; }
        public decimal margem_valor_st { get; set; }
        public decimal aliquota_icms_st { get; set; }
        public decimal reducao_base_icms { get; set; }
        public decimal base_calculo_operacao_propria { get; set; }
        public int motivo_desoneracao_icms { get; set; }
        public string ipi_classe_cigarro { get; set; }
        public string ipi_enquadramento_legal { get; set; }
        public string ipi_cnpj_produtor { get; set; }
        public int produto_especifico { get; set; }
        public Nullable<int> uf_id_icms_st { get; set; }
    
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
        public virtual ICollection<xerife_saldo_anterior_produto> xerife_saldo_anterior_produto { get; set; }
        public virtual ICollection<xerife_saldo_produto> xerife_saldo_produto { get; set; }
        public virtual ICollection<xerife_sped_c470> xerife_sped_c470 { get; set; }
        public virtual xerife_uf xerife_uf { get; set; }
        public virtual xerife_unidade xerife_unidade { get; set; }
        public virtual xerife_unidade xerife_unidade1 { get; set; }
    }
}
