//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_exposicao_fator_risco
    {
        public int exposicao_id { get; set; }
        public System.DateTime data_inicial { get; set; }
        public Nullable<System.DateTime> data_final { get; set; }
        public string tipo_risco { get; set; }
        public string fator_risco { get; set; }
        public string intensidade_concentracao { get; set; }
        public string tecnica_utilizada { get; set; }
        public bool epc { get; set; }
        public bool epi { get; set; }
        public string certificado_aprovacao_epi { get; set; }
        public int ppp_id { get; set; }
    
        public virtual xerife_ppp xerife_ppp { get; set; }
    }
}
