//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_movimentacao_sefip
    {
        public xerife_movimentacao_sefip()
        {
            this.xerife_funcionario_situacao = new HashSet<xerife_funcionario_situacao>();
        }
    
        public int movimentacao_id { get; set; }
        public string descricao { get; set; }
        public string codigo_sefip { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_funcionario_situacao> xerife_funcionario_situacao { get; set; }
    }
}
