//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_cargo
    {
        public xerife_cargo()
        {
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_piso_salarial = new HashSet<xerife_piso_salarial>();
        }
    
        public int cargo_id { get; set; }
        public string cbo { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_piso_salarial> xerife_piso_salarial { get; set; }
    }
}
