//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_conducao
    {
        public xerife_conducao()
        {
            this.xerife_conducao_funcionario = new HashSet<xerife_conducao_funcionario>();
            this.xerife_conducao_item = new HashSet<xerife_conducao_item>();
        }
    
        public int conducao_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_conducao_funcionario> xerife_conducao_funcionario { get; set; }
        public virtual ICollection<xerife_conducao_item> xerife_conducao_item { get; set; }
    }
}
