//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tabela_servico
    {
        public xerife_tabela_servico()
        {
            this.xerife_acumulador_servico = new HashSet<xerife_acumulador_servico>();
            this.xerife_item_issqn = new HashSet<xerife_item_issqn>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
        }
    
        public int tabela_servico_id { get; set; }
        public string descricao { get; set; }
        public string codigo { get; set; }
        public int classe { get; set; }
    
        public virtual ICollection<xerife_acumulador_servico> xerife_acumulador_servico { get; set; }
        public virtual ICollection<xerife_item_issqn> xerife_item_issqn { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
    }
}
