//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_parceiro_desconto
    {
        public int desconto_id { get; set; }
        public int referencia { get; set; }
        public string anotacao { get; set; }
        public decimal valor_desconto { get; set; }
        public int parceiro_id { get; set; }
        public string usuario { get; set; }
    
        public virtual xerife_parceiro xerife_parceiro { get; set; }
    }
}
