//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_plano_conta
    {
        public xerife_plano_conta()
        {
            this.xerife_contra_partida = new HashSet<xerife_contra_partida>();
            this.xerife_contra_partida1 = new HashSet<xerife_contra_partida>();
            this.xerife_empresa_contabil = new HashSet<xerife_empresa_contabil>();
            this.xerife_empresa_contabil1 = new HashSet<xerife_empresa_contabil>();
            this.xerife_empresa_contabil2 = new HashSet<xerife_empresa_contabil>();
            this.xerife_empresa_contabil3 = new HashSet<xerife_empresa_contabil>();
            this.xerife_empresa_contabil4 = new HashSet<xerife_empresa_contabil>();
            this.xerife_empresa_contabil5 = new HashSet<xerife_empresa_contabil>();
            this.xerife_integracao = new HashSet<xerife_integracao>();
            this.xerife_integracao1 = new HashSet<xerife_integracao>();
            this.xerife_lancamento_contabil = new HashSet<xerife_lancamento_contabil>();
            this.xerife_lancamento_contabil1 = new HashSet<xerife_lancamento_contabil>();
            this.xerife_plano_conta1 = new HashSet<xerife_plano_conta>();
            this.xerife_plano_conta11 = new HashSet<xerife_plano_conta>();
            this.xerife_plano_filial = new HashSet<xerife_plano_filial>();
        }
    
        public int plano_conta_id { get; set; }
        public Nullable<int> plano_conta_id_parente { get; set; }
        public Nullable<int> plano_conta_id_depreciacao { get; set; }
        public int codigo { get; set; }
        public int digito { get; set; }
        public int empresa_id { get; set; }
        public string descricao { get; set; }
        public int ordem { get; set; }
        public int grau { get; set; }
        public string sinal { get; set; }
        public int tipo { get; set; }
        public byte[] controlversion { get; set; }
        public string conta_sped { get; set; }
        public int natureza { get; set; }
        public bool importacao { get; set; }
        public Nullable<System.DateTime> data_importacao { get; set; }
        public int conta_dre { get; set; }
        public int conta_dlpa { get; set; }
        public int tipo_caixa { get; set; }
    
        public virtual ICollection<xerife_contra_partida> xerife_contra_partida { get; set; }
        public virtual ICollection<xerife_contra_partida> xerife_contra_partida1 { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil1 { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil2 { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil3 { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil4 { get; set; }
        public virtual ICollection<xerife_empresa_contabil> xerife_empresa_contabil5 { get; set; }
        public virtual ICollection<xerife_integracao> xerife_integracao { get; set; }
        public virtual ICollection<xerife_integracao> xerife_integracao1 { get; set; }
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil { get; set; }
        public virtual ICollection<xerife_lancamento_contabil> xerife_lancamento_contabil1 { get; set; }
        public virtual ICollection<xerife_plano_conta> xerife_plano_conta1 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta2 { get; set; }
        public virtual ICollection<xerife_plano_conta> xerife_plano_conta11 { get; set; }
        public virtual xerife_plano_conta xerife_plano_conta3 { get; set; }
        public virtual ICollection<xerife_plano_filial> xerife_plano_filial { get; set; }
    }
}
