//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_mensagem
    {
        public xerife_mensagem()
        {
            this.xerife_anexo_mensagem = new HashSet<xerife_anexo_mensagem>();
        }
    
        public int mensagem_id { get; set; }
        public string remetente { get; set; }
        public string destinatario { get; set; }
        public string destinarios_emcopia { get; set; }
        public System.DateTime data_envio { get; set; }
        public Nullable<System.DateTime> data_leitura { get; set; }
        public string assunto { get; set; }
        public string conteudo { get; set; }
        public Nullable<int> pasta_id { get; set; }
    
        public virtual ICollection<xerife_anexo_mensagem> xerife_anexo_mensagem { get; set; }
        public virtual xerife_pasta_mensagem xerife_pasta_mensagem { get; set; }
    }
}
