//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_configuracao_folha
    {
        public int configuracao_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public decimal salario_minimo { get; set; }
        public decimal deducao_irrf { get; set; }
        public decimal irrf_65anos { get; set; }
        public decimal minimo_irrf { get; set; }
        public decimal total_remuneracao_dirf { get; set; }
    }
}
