//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_indice
    {
        public xerife_indice()
        {
            this.xerife_indice_item = new HashSet<xerife_indice_item>();
            this.xerife_sindicato = new HashSet<xerife_sindicato>();
            this.xerife_sindicato1 = new HashSet<xerife_sindicato>();
            this.xerife_sindicato2 = new HashSet<xerife_sindicato>();
        }
    
        public int indice_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_indice_item> xerife_indice_item { get; set; }
        public virtual ICollection<xerife_sindicato> xerife_sindicato { get; set; }
        public virtual ICollection<xerife_sindicato> xerife_sindicato1 { get; set; }
        public virtual ICollection<xerife_sindicato> xerife_sindicato2 { get; set; }
    }
}
