//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_outras_receitas_item
    {
        public int outras_receitas_item_id { get; set; }
        public int outras_receitas_id { get; set; }
        public int item_id { get; set; }
        public decimal valor { get; set; }
        public decimal percentual { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_outras_receitas xerife_outras_receitas { get; set; }
    }
}
