//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_funcionario_situacao
    {
        public int funcionario_situacao_id { get; set; }
        public int funcionario_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public System.DateTime afastamento { get; set; }
        public Nullable<System.DateTime> retorno { get; set; }
        public int situacao { get; set; }
        public int codigo_afastamento { get; set; }
        public Nullable<int> movimentacao_id { get; set; }
        public int agrupamento { get; set; }
        public Nullable<int> filial_transferencia_destino_id { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
        public virtual xerife_movimentacao_sefip xerife_movimentacao_sefip { get; set; }
    }
}
