//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_regra_acesso
    {
        public xerife_regra_acesso()
        {
            this.xerife_regra_acesso_item = new HashSet<xerife_regra_acesso_item>();
            this.xerife_usuario = new HashSet<xerife_usuario>();
        }
    
        public int regra_acesso_id { get; set; }
        public string nome_acesso { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_regra_acesso_item> xerife_regra_acesso_item { get; set; }
        public virtual ICollection<xerife_usuario> xerife_usuario { get; set; }
    }
}
