//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_livro_fiscal_item
    {
        public int livro_fiscal_item_id { get; set; }
        public int livro_fiscal_id { get; set; }
        public int filial_id { get; set; }
        public int ano { get; set; }
        public int livro { get; set; }
        public int inicial { get; set; }
        public int janeiro { get; set; }
        public int fevereiro { get; set; }
        public int marco { get; set; }
        public int abril { get; set; }
        public int maio { get; set; }
        public int junho { get; set; }
        public int julho { get; set; }
        public int agosto { get; set; }
        public int setembro { get; set; }
        public int outubro { get; set; }
        public int novembro { get; set; }
        public int dezembro { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_livro_fiscal xerife_livro_fiscal { get; set; }
    }
}
