//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_parceiro
    {
        public xerife_parceiro()
        {
            this.xerife_anotacao_parceiro = new HashSet<xerife_anotacao_parceiro>();
            this.xerife_filial = new HashSet<xerife_filial>();
            this.xerife_item_transporte = new HashSet<xerife_item_transporte>();
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
            this.xerife_parceiro_desconto = new HashSet<xerife_parceiro_desconto>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
            this.xerife_titulo1 = new HashSet<xerife_titulo>();
        }
    
        public int parceiro_id { get; set; }
        public int empresa_id { get; set; }
        public string razao_social { get; set; }
        public string fantasia { get; set; }
        public int tipo_contribuicao { get; set; }
        public int tipo { get; set; }
        public int modelo { get; set; }
        public string cpf { get; set; }
        public string cnpj { get; set; }
        public string cei { get; set; }
        public string inscricao_estadual { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string cep { get; set; }
        public string complemento { get; set; }
        public string numero { get; set; }
        public string telefone { get; set; }
        public string celular { get; set; }
        public string fax { get; set; }
        public string email { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public int tipo_parceiro { get; set; }
        public Nullable<int> regime_tributario_id { get; set; }
        public string inscricao_municipal { get; set; }
        public bool acessibilidade_global { get; set; }
        public Nullable<int> municipio_cobranca_id { get; set; }
        public string endereco_cobranca { get; set; }
        public string bairro_cobranca { get; set; }
        public string cep_cobranca { get; set; }
        public bool ativo { get; set; }
        public int dia_vencimento { get; set; }
        public decimal valor_contratual { get; set; }
        public Nullable<System.Guid> anexo_id { get; set; }
        public string anotacao { get; set; }
        public string website { get; set; }
        public Nullable<int> tipo_parceiro_id { get; set; }
        public string numero_contrato { get; set; }
        public Nullable<int> tipo_contrato_id { get; set; }
        public Nullable<int> conta_bancaria_id { get; set; }
    
        public virtual ICollection<xerife_anotacao_parceiro> xerife_anotacao_parceiro { get; set; }
        public virtual xerife_conta_bancaria xerife_conta_bancaria { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_filial> xerife_filial { get; set; }
        public virtual ICollection<xerife_item_transporte> xerife_item_transporte { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_municipio xerife_municipio1 { get; set; }
        public virtual ICollection<xerife_parceiro_desconto> xerife_parceiro_desconto { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo1 { get; set; }
        public virtual xerife_regime_tributario xerife_regime_tributario { get; set; }
        public virtual xerife_tipo_contrato xerife_tipo_contrato { get; set; }
        public virtual xerife_tipo_parceiro xerife_tipo_parceiro { get; set; }
    }
}
