//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_anexo_mensagem
    {
        public int anexo_mensagem_id { get; set; }
        public string arquivo { get; set; }
        public byte[] conteudo { get; set; }
        public int mensagem_id { get; set; }
    
        public virtual xerife_mensagem xerife_mensagem { get; set; }
    }
}
