//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_variavel
    {
        public xerife_variavel()
        {
            this.xerife_evento = new HashSet<xerife_evento>();
            this.xerife_variavel_valor = new HashSet<xerife_variavel_valor>();
        }
    
        public int variavel_id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_evento> xerife_evento { get; set; }
        public virtual ICollection<xerife_variavel_valor> xerife_variavel_valor { get; set; }
    }
}
