//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tipo_evento
    {
        public xerife_tipo_evento()
        {
            this.xerife_evento = new HashSet<xerife_evento>();
        }
    
        public int tipo_evento_id { get; set; }
        public string descricao { get; set; }
        public string tipo_padrao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_evento> xerife_evento { get; set; }
    }
}
