//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_lancamento_servico
    {
        public int item_lancamento_servico_id { get; set; }
        public decimal valor_base { get; set; }
        public decimal valor_deducao { get; set; }
        public decimal aliquota { get; set; }
        public decimal valor_credito { get; set; }
        public decimal valor_imposto { get; set; }
        public string anotacoes { get; set; }
        public byte[] controlversion { get; set; }
        public int lancamento_servico_id { get; set; }
        public int item_regime_tributario_id { get; set; }
        public Nullable<int> tabela_id { get; set; }
    
        public virtual xerife_item_regime_tributario xerife_item_regime_tributario { get; set; }
        public virtual xerife_lancamento_servico xerife_lancamento_servico { get; set; }
        public virtual xerife_tabela xerife_tabela { get; set; }
    }
}
