//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_saldo_patrimonio
    {
        public long saldo_patrimonio_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public decimal debito { get; set; }
        public decimal credito { get; set; }
        public decimal debito_depreciacao { get; set; }
        public decimal credito_depreciacao { get; set; }
        public decimal debito_encerramento { get; set; }
        public decimal credito_encerramento { get; set; }
        public byte[] controlversion { get; set; }
        public int patrimonio_id { get; set; }
    
        public virtual xerife_patrimonio xerife_patrimonio { get; set; }
    }
}
