//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_filial
    {
        public xerife_filial()
        {
            this.xerife_acumulador_fiscal = new HashSet<xerife_acumulador_fiscal>();
            this.xerife_acumulador_guia = new HashSet<xerife_acumulador_guia>();
            this.xerife_acumulador_servico = new HashSet<xerife_acumulador_servico>();
            this.xerife_apuracao_imposto = new HashSet<xerife_apuracao_imposto>();
            this.xerife_arquivo_bancario = new HashSet<xerife_arquivo_bancario>();
            this.xerife_bloqueio_mensal = new HashSet<xerife_bloqueio_mensal>();
            this.xerife_conta_bancaria = new HashSet<xerife_conta_bancaria>();
            this.xerife_conta_financeira = new HashSet<xerife_conta_financeira>();
            this.xerife_deducoes = new HashSet<xerife_deducoes>();
            this.xerife_estoque = new HashSet<xerife_estoque>();
            this.xerife_estorno = new HashSet<xerife_estorno>();
            this.xerife_evento_filial = new HashSet<xerife_evento_filial>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
            this.xerife_funcionario = new HashSet<xerife_funcionario>();
            this.xerife_funcionario_situacao = new HashSet<xerife_funcionario_situacao>();
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_fiscal1 = new HashSet<xerife_lancamento_fiscal>();
            this.xerife_lancamento_servico = new HashSet<xerife_lancamento_servico>();
            this.xerife_livro_fiscal_item = new HashSet<xerife_livro_fiscal_item>();
            this.xerife_mapeamento_tabela = new HashSet<xerife_mapeamento_tabela>();
            this.xerife_outras_receitas = new HashSet<xerife_outras_receitas>();
            this.xerife_permissao_filial = new HashSet<xerife_permissao_filial>();
            this.xerife_plano_filial = new HashSet<xerife_plano_filial>();
            this.xerife_plano_saude_filial = new HashSet<xerife_plano_saude_filial>();
            this.xerife_protocolo = new HashSet<xerife_protocolo>();
            this.xerife_situacao_fiscal = new HashSet<xerife_situacao_fiscal>();
            this.xerife_vale_valor = new HashSet<xerife_vale_valor>();
            this.xerife_requisicao = new HashSet<xerife_requisicao>();
        }
    
        public int filial_id { get; set; }
        public string nome { get; set; }
        public string cnpj_cei { get; set; }
        public int empresa_id { get; set; }
        public bool ativo { get; set; }
        public System.DateTime data_abertura { get; set; }
        public bool matriz { get; set; }
        public byte[] controlversion { get; set; }
        public string inscricao_estadual { get; set; }
        public string inscricao_municipal { get; set; }
        public string endereco { get; set; }
        public string bairro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string cep { get; set; }
        public string telefone { get; set; }
        public string fax { get; set; }
        public string numero_registro { get; set; }
        public Nullable<System.DateTime> data_registro { get; set; }
        public int orgao_registro { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public Nullable<int> parceiro_id { get; set; }
        public Nullable<int> contador_id { get; set; }
        public int qualificacao_assinante { get; set; }
        public int livro_diario { get; set; }
        public int livro_caixa { get; set; }
        public int livro_razao { get; set; }
        public int livro_sped { get; set; }
        public Nullable<System.DateTime> data_encerramento { get; set; }
        public string distrito { get; set; }
        public string sub_distrito { get; set; }
        public string nome_orgao_registro { get; set; }
        public Nullable<int> gps_id { get; set; }
        public Nullable<int> fpas_id { get; set; }
        public Nullable<int> natureza_juridica_id { get; set; }
        public Nullable<int> regime_tributario_id { get; set; }
        public Nullable<int> recolhimento_sefip_id { get; set; }
        public Nullable<System.DateTime> referencia_gps { get; set; }
        public Nullable<System.DateTime> referencia_darf { get; set; }
        public Nullable<int> sindicato_id { get; set; }
        public Nullable<int> infaz_id { get; set; }
        public decimal fap { get; set; }
        public int mes_base_dissidio { get; set; }
        public Nullable<int> cnae_servico_id { get; set; }
        public Nullable<int> cnae_produto_id { get; set; }
        public Nullable<int> moeda_id_aprazo { get; set; }
        public Nullable<int> moeda_id_avista { get; set; }
        public int cnae_principal { get; set; }
        public decimal aliquota_servico { get; set; }
        public string email { get; set; }
        public Nullable<System.Guid> anexo_id { get; set; }
        public int emite_nfse { get; set; }
        public int contador_rps { get; set; }
        public decimal saldo_inicial_icms { get; set; }
        public decimal saldo_inicial_ipi { get; set; }
        public Nullable<System.DateTime> data_saldo_inicial_icms { get; set; }
        public Nullable<System.DateTime> data_saldo_inicial_ipi { get; set; }
        public decimal aliquota_pis { get; set; }
        public decimal aliquota_cofins { get; set; }
        public int cst_pis { get; set; }
        public int cst_cofins { get; set; }
        public int tipo_sped { get; set; }
        public int contador_lote { get; set; }
        public int tipo_regime_servico { get; set; }
        public string senha_portal { get; set; }
        public string salt_senha_portal { get; set; }
        public int configuracao { get; set; }
        public int emite_nfe { get; set; }
        public int contador_lote_nfe { get; set; }
        public int dia_adiantamento_quizenal { get; set; }
        public int tipo_empresa { get; set; }
        public Nullable<int> tipo_sistema_ponto { get; set; }
        public string sip_orgao { get; set; }
        public string sip_unidade_orcamentaria { get; set; }
        public string sip_unidade_despesa { get; set; }
        public string sip_unidade_administrativa { get; set; }
        public string sip_unidade_locacao { get; set; }
        public string sip_regiao_administrativa { get; set; }
        public string sip_municipio { get; set; }
    
        public virtual ICollection<xerife_acumulador_fiscal> xerife_acumulador_fiscal { get; set; }
        public virtual ICollection<xerife_acumulador_guia> xerife_acumulador_guia { get; set; }
        public virtual ICollection<xerife_acumulador_servico> xerife_acumulador_servico { get; set; }
        public virtual ICollection<xerife_apuracao_imposto> xerife_apuracao_imposto { get; set; }
        public virtual ICollection<xerife_arquivo_bancario> xerife_arquivo_bancario { get; set; }
        public virtual ICollection<xerife_bloqueio_mensal> xerife_bloqueio_mensal { get; set; }
        public virtual xerife_cnae xerife_cnae { get; set; }
        public virtual xerife_cnae xerife_cnae1 { get; set; }
        public virtual ICollection<xerife_conta_bancaria> xerife_conta_bancaria { get; set; }
        public virtual ICollection<xerife_conta_financeira> xerife_conta_financeira { get; set; }
        public virtual xerife_contador xerife_contador { get; set; }
        public virtual ICollection<xerife_deducoes> xerife_deducoes { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
        public virtual ICollection<xerife_estoque> xerife_estoque { get; set; }
        public virtual ICollection<xerife_estorno> xerife_estorno { get; set; }
        public virtual ICollection<xerife_evento_filial> xerife_evento_filial { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
        public virtual ICollection<xerife_funcionario> xerife_funcionario { get; set; }
        public virtual ICollection<xerife_funcionario_situacao> xerife_funcionario_situacao { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal1 { get; set; }
        public virtual ICollection<xerife_lancamento_servico> xerife_lancamento_servico { get; set; }
        public virtual ICollection<xerife_livro_fiscal_item> xerife_livro_fiscal_item { get; set; }
        public virtual ICollection<xerife_mapeamento_tabela> xerife_mapeamento_tabela { get; set; }
        public virtual ICollection<xerife_outras_receitas> xerife_outras_receitas { get; set; }
        public virtual ICollection<xerife_permissao_filial> xerife_permissao_filial { get; set; }
        public virtual ICollection<xerife_plano_filial> xerife_plano_filial { get; set; }
        public virtual ICollection<xerife_plano_saude_filial> xerife_plano_saude_filial { get; set; }
        public virtual ICollection<xerife_protocolo> xerife_protocolo { get; set; }
        public virtual ICollection<xerife_situacao_fiscal> xerife_situacao_fiscal { get; set; }
        public virtual ICollection<xerife_vale_valor> xerife_vale_valor { get; set; }
        public virtual xerife_fpas xerife_fpas { get; set; }
        public virtual xerife_gps xerife_gps { get; set; }
        public virtual xerife_infaz xerife_infaz { get; set; }
        public virtual xerife_moeda xerife_moeda { get; set; }
        public virtual xerife_moeda xerife_moeda1 { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_natureza_juridica xerife_natureza_juridica { get; set; }
        public virtual xerife_parceiro xerife_parceiro { get; set; }
        public virtual xerife_recolhimento_sefip xerife_recolhimento_sefip { get; set; }
        public virtual xerife_regime_tributario xerife_regime_tributario { get; set; }
        public virtual xerife_sindicato xerife_sindicato { get; set; }
        public virtual ICollection<xerife_requisicao> xerife_requisicao { get; set; }
    }
}
