//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_protocolo
    {
        public xerife_protocolo()
        {
            this.xerife_documento_portal = new HashSet<xerife_documento_portal>();
        }
    
        public int protocolo_id { get; set; }
        public Nullable<int> filial_id { get; set; }
        public int tipo_documento_id { get; set; }
        public string descricao { get; set; }
        public int tipo { get; set; }
        public System.DateTime data_protocolo { get; set; }
        public int situacao { get; set; }
        public System.DateTime data_situacao { get; set; }
        public Nullable<System.DateTime> data_vencimento { get; set; }
        public decimal valor { get; set; }
        public string portador { get; set; }
        public string receptor { get; set; }
        public string local_arquivamento { get; set; }
        public Nullable<System.DateTime> prazo_retorno { get; set; }
        public string anotacao { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<System.DateTime> ultima_visualizacao_portal { get; set; }
    
        public virtual ICollection<xerife_documento_portal> xerife_documento_portal { get; set; }
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_tipo_documento xerife_tipo_documento { get; set; }
    }
}
