//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_arquivo
    {
        public xerife_arquivo()
        {
            this.xerife_documento = new HashSet<xerife_documento>();
        }
    
        public int arquivo_id { get; set; }
        public string nome { get; set; }
        public int tamanho { get; set; }
        public byte[] conteudo { get; set; }
    
        public virtual ICollection<xerife_documento> xerife_documento { get; set; }
    }
}
