//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_documento_portal
    {
        public System.Guid documento_portal { get; set; }
        public string cloud_id { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public int tamanho { get; set; }
        public int tipo_documento_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public Nullable<System.Guid> anexo_id { get; set; }
        public int downloads { get; set; }
        public Nullable<System.DateTime> data_ultimo_download { get; set; }
        public System.DateTime data_upload { get; set; }
        public bool cancelado { get; set; }
        public Nullable<int> protocolo_id { get; set; }
    
        public virtual xerife_protocolo xerife_protocolo { get; set; }
        public virtual xerife_tipo_documento xerife_tipo_documento { get; set; }
    }
}
