//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_sped_c470
    {
        public int sped_c470__id { get; set; }
        public decimal quantidade { get; set; }
        public decimal quantidade_cancelada { get; set; }
        public decimal valor_item { get; set; }
        public int cst_icms { get; set; }
        public decimal aliquota_icms { get; set; }
        public decimal valor_pis { get; set; }
        public decimal valor_cofins { get; set; }
        public Nullable<int> produto_id { get; set; }
        public Nullable<int> codigo_fiscal_id { get; set; }
        public int sped_c460_id { get; set; }
    
        public virtual xerife_codigo_fiscal xerife_codigo_fiscal { get; set; }
        public virtual xerife_produto xerife_produto { get; set; }
        public virtual xerife_sped_c460 xerife_sped_c460 { get; set; }
    }
}
