//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_regra
    {
        public xerife_regra()
        {
            this.xerife_configuracao = new HashSet<xerife_configuracao>();
            this.xerife_permissao_regra = new HashSet<xerife_permissao_regra>();
            this.xerife_usuario_regra = new HashSet<xerife_usuario_regra>();
        }
    
        public int regra_id { get; set; }
        public string nome_regra { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public bool uso_interno { get; set; }
        public bool ativo { get; set; }
    
        public virtual ICollection<xerife_configuracao> xerife_configuracao { get; set; }
        public virtual ICollection<xerife_permissao_regra> xerife_permissao_regra { get; set; }
        public virtual ICollection<xerife_usuario_regra> xerife_usuario_regra { get; set; }
    }
}
