//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_deducoes
    {
        public int deducoes_id { get; set; }
        public int filial_id { get; set; }
        public int imposto_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public int periodo { get; set; }
        public decimal valor_base { get; set; }
        public decimal valor_imposto { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_filial xerife_filial { get; set; }
        public virtual xerife_imposto xerife_imposto { get; set; }
    }
}
