//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_pasta_mensagem
    {
        public xerife_pasta_mensagem()
        {
            this.xerife_mensagem = new HashSet<xerife_mensagem>();
        }
    
        public int pasta_id { get; set; }
        public string descricao { get; set; }
        public int cor { get; set; }
        public int tag { get; set; }
        public byte[] controlversion { get; set; }
        public int usuario_id { get; set; }
    
        public virtual ICollection<xerife_mensagem> xerife_mensagem { get; set; }
        public virtual xerife_usuario xerife_usuario { get; set; }
    }
}
