//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_conducao_funcionario
    {
        public int conducao_funcionario_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public int quantidade { get; set; }
        public int conducao_id { get; set; }
        public int funcionario_id { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_conducao xerife_conducao { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
