//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_integracao_generica
    {
        public int integracao_id { get; set; }
        public string codigo_integracao { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual xerife_integracao xerife_integracao { get; set; }
    }
}
