//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tabela_item
    {
        public int tabela_item_id { get; set; }
        public System.DateTime exercicio { get; set; }
        public decimal valor_inicial { get; set; }
        public decimal valor_final { get; set; }
        public decimal percentual { get; set; }
        public decimal valor { get; set; }
        public int tabela_id { get; set; }
        public byte[] controlversion { get; set; }
        public decimal irpj { get; set; }
        public decimal csll { get; set; }
        public decimal cofins { get; set; }
        public decimal pis { get; set; }
        public decimal cpp { get; set; }
        public decimal icms { get; set; }
        public decimal ipi { get; set; }
        public decimal iss { get; set; }
    
        public virtual xerife_tabela xerife_tabela { get; set; }
    }
}
