//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_tipo_documento
    {
        public xerife_tipo_documento()
        {
            this.xerife_documento = new HashSet<xerife_documento>();
            this.xerife_documento_portal = new HashSet<xerife_documento_portal>();
            this.xerife_protocolo = new HashSet<xerife_protocolo>();
        }
    
        public int tipo_documento_id { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public int visualizacao { get; set; }
        public bool uso_interno { get; set; }
    
        public virtual ICollection<xerife_documento> xerife_documento { get; set; }
        public virtual ICollection<xerife_documento_portal> xerife_documento_portal { get; set; }
        public virtual ICollection<xerife_protocolo> xerife_protocolo { get; set; }
    }
}
