//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_fiscal
    {
        public int item_fiscal_id { get; set; }
        public int lancamento_fiscal_id { get; set; }
        public decimal valor_base { get; set; }
        public decimal aliquota { get; set; }
        public decimal valor_imposto { get; set; }
        public decimal valor_isentas { get; set; }
        public decimal valor_outras { get; set; }
        public string anotacoes { get; set; }
        public decimal tva { get; set; }
        public decimal valor_icms { get; set; }
        public int codigo_fiscal_id { get; set; }
        public int item_regime_tributario_id { get; set; }
        public Nullable<int> detalhamento_fiscal_id { get; set; }
        public Nullable<int> tabela_id { get; set; }
    
        public virtual xerife_codigo_fiscal xerife_codigo_fiscal { get; set; }
        public virtual xerife_detalhamento_fiscal xerife_detalhamento_fiscal { get; set; }
        public virtual xerife_item_regime_tributario xerife_item_regime_tributario { get; set; }
        public virtual xerife_lancamento_fiscal xerife_lancamento_fiscal { get; set; }
        public virtual xerife_tabela xerife_tabela { get; set; }
    }
}
