//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_detalhamento_fiscal
    {
        public xerife_detalhamento_fiscal()
        {
            this.xerife_item_produto = new HashSet<xerife_item_produto>();
            this.xerife_item_fiscal = new HashSet<xerife_item_fiscal>();
        }
    
        public int detalhamento_fiscal_id { get; set; }
        public string descricao { get; set; }
        public int empresa_id { get; set; }
        public byte[] controlversion { get; set; }
    
        public virtual ICollection<xerife_item_produto> xerife_item_produto { get; set; }
        public virtual ICollection<xerife_item_fiscal> xerife_item_fiscal { get; set; }
        public virtual xerife_empresa xerife_empresa { get; set; }
    }
}
