//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_item_transporte
    {
        public xerife_item_transporte()
        {
            this.xerife_lancamento_fiscal = new HashSet<xerife_lancamento_fiscal>();
        }
    
        public int item_transporte_id { get; set; }
        public Nullable<int> parceiro_id { get; set; }
        public string placa { get; set; }
        public Nullable<int> uf_id_placa { get; set; }
        public string placa_reboque { get; set; }
        public Nullable<int> uf_id_reboque { get; set; }
        public string rntc_placa { get; set; }
        public string rntc_reboque { get; set; }
        public string balsa { get; set; }
        public string vagao { get; set; }
        public int quantidade { get; set; }
        public string especie { get; set; }
        public string marca { get; set; }
        public string numeracao { get; set; }
        public decimal peso_liquido { get; set; }
        public decimal peso_bruto { get; set; }
        public string lacres { get; set; }
        public decimal valor_servico { get; set; }
        public byte[] controlversion { get; set; }
        public Nullable<int> codigo_fiscal_id { get; set; }
        public Nullable<int> municipio_id { get; set; }
        public decimal base_calculo_pis { get; set; }
        public decimal aliquota_pis { get; set; }
        public decimal valor_pis { get; set; }
        public decimal quantidade_pis { get; set; }
        public decimal valor_unitario_pis { get; set; }
        public decimal base_calculo_cofins { get; set; }
        public decimal aliquota_cofins { get; set; }
        public decimal valor_cofins { get; set; }
        public decimal quantidade_cofins { get; set; }
        public decimal valor_unitario_cofins { get; set; }
        public decimal credito_icms { get; set; }
        public Nullable<int> natureza_base_credito_cofins { get; set; }
        public Nullable<int> natureza_base_credito_pis { get; set; }
        public string chave_cte_ref { get; set; }
        public Nullable<int> tipo_cte { get; set; }
        public Nullable<int> modal { get; set; }
        public Nullable<int> tipo_servico { get; set; }
        public Nullable<int> cst_pis { get; set; }
        public Nullable<int> cst_cofins { get; set; }
        public Nullable<int> cst_icms { get; set; }
        public Nullable<int> tipo_receita { get; set; }
        public Nullable<int> indicador_natureza_frete { get; set; }
    
        public virtual xerife_codigo_fiscal xerife_codigo_fiscal { get; set; }
        public virtual ICollection<xerife_lancamento_fiscal> xerife_lancamento_fiscal { get; set; }
        public virtual xerife_municipio xerife_municipio { get; set; }
        public virtual xerife_parceiro xerife_parceiro { get; set; }
        public virtual xerife_uf xerife_uf { get; set; }
        public virtual xerife_uf xerife_uf1 { get; set; }
    }
}
