//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_banco
    {
        public xerife_banco()
        {
            this.xerife_conta_bancaria = new HashSet<xerife_conta_bancaria>();
            this.xerife_funcionario_dados = new HashSet<xerife_funcionario_dados>();
            this.xerife_funcionario_dados1 = new HashSet<xerife_funcionario_dados>();
            this.xerife_titulo = new HashSet<xerife_titulo>();
        }
    
        public int banco_id { get; set; }
        public string codigo { get; set; }
        public string descricao { get; set; }
        public byte[] controlversion { get; set; }
        public string dac_banco { get; set; }
    
        public virtual ICollection<xerife_conta_bancaria> xerife_conta_bancaria { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados { get; set; }
        public virtual ICollection<xerife_funcionario_dados> xerife_funcionario_dados1 { get; set; }
        public virtual ICollection<xerife_titulo> xerife_titulo { get; set; }
    }
}
