//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_folha
    {
        public long folha_id { get; set; }
        public string exercicio { get; set; }
        public int situacao { get; set; }
        public Nullable<System.DateTime> data_referencia { get; set; }
        public System.DateTime data_processamento { get; set; }
        public int tipo_lancamento { get; set; }
        public decimal valor_base { get; set; }
        public decimal quantidade { get; set; }
        public decimal saldo { get; set; }
        public decimal provento { get; set; }
        public decimal desconto { get; set; }
        public decimal teto { get; set; }
        public int plano { get; set; }
        public int parcela { get; set; }
        public int bloqueio { get; set; }
        public byte[] controlversion { get; set; }
        public int evento_id { get; set; }
        public int funcionario_id { get; set; }
        public int codigo_importacao { get; set; }
        public string usuario { get; set; }
        public int agrupamento { get; set; }
        public string descricao { get; set; }
        public Nullable<int> flag_incidencia { get; set; }
        public string memoria_referencia { get; set; }
        public string memoria_valor { get; set; }
    
        public virtual xerife_evento xerife_evento { get; set; }
        public virtual xerife_funcionario xerife_funcionario { get; set; }
    }
}
