//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xerife.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class xerife_sped_c490
    {
        public int sped_c490_id { get; set; }
        public int cst_icms { get; set; }
        public int codigo_fiscal_id { get; set; }
        public decimal aliq_icms { get; set; }
        public decimal vl_opr { get; set; }
        public decimal vl_bc_icms { get; set; }
        public decimal vl_icms { get; set; }
        public string cod_obs { get; set; }
        public int lancamento_fiscal_id { get; set; }
    
        public virtual xerife_codigo_fiscal xerife_codigo_fiscal { get; set; }
        public virtual xerife_lancamento_fiscal xerife_lancamento_fiscal { get; set; }
    }
}
